global:
  scrape_interval: 15s
  scrape_timeout: 10s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: nexus-host
    static_configs:
      - targets: [':9100'] # Server IP:PORT (Node-Exporter)

  - job_name: pve
    metrics_path: /pve
    static_configs:
      - targets: ['pve-exporter:9221']
    params:
      target: [''] # Server IP
    relabel_configs:
      - source_labels: [__param_target]
        target_label: instance
