apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: velero
  namespace: argocd
spec:
  destination:
    namespace: velero
    server: https://kubernetes.default.svc
  sources:
    - repoURL: https://vmware-tanzu.github.io/helm-charts
      chart: velero
      targetRevision: 11.3.2
      helm:
        valueFiles:
          - $values/k3s/infra/velero/values.yaml

    - repoURL: https://github.com/manos-grigorakis/home-lab.git
      targetRevision: main
      path: k3s/infra/velero
      ref: values
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
