apiVersion: v1
kind: Service
metadata:
  name: immich-database
  namespace: immich
spec:
  selector:
    app: immich-database
  ports:
    - name: tcp-postgres
      port: 5432
      targetPort: 5432
      protocol: TCP 
  type: ClusterIP