apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-dashboard
  namespace: kube-system
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`traefik.k3s.poolnode.net`)
      kind: Rule
      services:
        - name: api@internal
          kind: TraefikService
  tls: 
    secretName: k3s-wildcard-tls
