apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wazuh-indexer-cert
  namespace: wazuh
spec:
  secretName: wazuh-indexer-cert
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
  dnsNames:
    - indexer.wazuh.svc
    - indexer.wazuh.svc.cluster.local
    - wazuh-indexer-0.wazuh-indexer.wazuh.svc
    - wazuh-indexer-0.wazuh-indexer.wazuh.svc.cluster.local
  issuerRef:
    name: wazuh-ca-issuer
    kind: Issuer
    group: cert-manager.io

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wazuh-indexer-admin-cert
  namespace: wazuh
spec:
  secretName: wazuh-indexer-admin-cert
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - client auth
  subject:
    organizations: ["wazuh"]
  commonName: admin
  issuerRef:
    name: wazuh-ca-issuer
    kind: Issuer
    group: cert-manager.io
