---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: velero-credentials
  namespace: velero
spec:
  encryptedData:
    cloud: AgDOeyGuQribGHgQjgT36b3Rjn0ba+v4p6iM/wkiArh6myHVioZW6sSAUdz0HzwezQiHSf6Yz5O2OD8ElvVKUFz7pkEqfqvWJIuO7pghydeUZkasGMHYxoyFMJv281sjen/dOeflsFN5TfXCwb8mtmolMfH6uZ2FmcwCuRHkKEzVFeDDfnntyfVP0Alzutp1dbaDv7EZ/5UCbPPKPfNqwOdeZCE1YYD0fh4J5QLlb13lk6eXL6Mbk9lPTPNtG+9aSnNIY7ROhwQuUKL/8iui1O5hZQicLWrRTKSkax0fbOksR1SWJweztHai4ojc/m12OnthIb8H2HiusM9DVA/ypNIZwtVfiDLJox3NVgITmdZANJx/OnqWTZYB0Ryw+fHMRO2fv58YKXVZmFIGJ13zT8WJiWKFO/ejgQR4FD1ifB//QO3Vji2pXsrjjCpZm1J+bgCg0x/ZFBRdmfofLBAD0o8kiWM/1+jYt4EW80p8ASoz9DPKHG6eTMZSitrRbwihQvzu6uKdBaXw6mEoK/mRvDjl1swOewbDdo6g2HaGbvnwrfOS2q9/W1PE4opfkj2X0ysk8D8MHawy+4ejrEnMyoRItu0TqKmiLAI81yJqnhd9qgJjYC3SA/vKnbjHAjDLJib/QOldEEJh+yDiAykw8QvakXm9UGtK0Fxtwc0/1F4QFk1Ty9VkCA/jJVPqnIFWMiILRjOs+LO4EBl7a35YAuBg3ppAw12wYMA6rxutR3WNntiUqWIqdbdI/6yfSYrE5GXofk+Xm50GuQwSdv0U9C1t7FzY7a0e6v5qCbbYnCFd
  template:
    metadata:
      name: velero-credentials
      namespace: velero
    type: Opaque
