---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-cred-secret
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgAgl/Z2Nt4ZhCclg5pA8rZunjqtVJAQqtj/2GnUN2x3Ms5zOQDHbTOjkhcKqUi92eQO/QLp6Tf/RAreV5/nubpWivnXCQCC+jp/NNIQgeSdml7z6inBSTaCbR4o1lZmWqUzz61JwqL9PXzCksNGFF4qEYeh3fVgh5an3MzcqzKRfE0+ps3JgaYPL8ufX85NUQ1cNSu6bFQnLQivsp1LSDHRnLB6E5aRidMq/1UvD6oegVV3b/aMYxQ3pquGTNBHtzIZTe2h/7XiNP9qExAfKO6MIWtd4f3/TlPjfN0rVO4sl6Vu1ytg8DFIIpgX51UL3UpxabbQX+AIja7k2bG9R+UZ134gqt5U4VidNQalIp2GgimF0GjPmtgasreMK98/8imY/88m/f6vYBuUsDJmuA0IxzrHJsj4bpLvXEALpE5bAY9rqvggF2CuuWchvGBKrOe2ZhDBl2GFkpdAUq36qap2Mr8TBBn+zx4OnxpivZmuDefoRkPOSz4nZb2vlk3SrAA66Icpm8FaQRp0FPg3AIguSy1+FuuKxvN6T1yJzSl2oG8nAZ276Pt+cAQDfkEPNVj741MMO5and2pAX7gsbt/gPqezT6mhVx/51JMLrTvQ/P6bPksG0QohXwUZBHgX8fvUbEpi5KkmU+f8Hi4PANxRV5/nZB5UUhU4NWo2TxXaZuRWHbIpKXHU/poaTEPl+7ua65Bbl3Hszg==
    admin-user: AgA4m0w10d5gPxeueKi1kGY/ZaxUoXLd686eFRAkoL8Pt4UQG1yjCnVHSnNh5PgwGA+W69eRASCXP5DjsCD4F+SA9JGOEdaPMLbnqGwRF4DSKr7iCKTKRJIqXCW1zlORuR9TFiV6MiiWsZcWxrOcXtY13lGcN+2Xd2hw+E1Vd14GeYtAIkfqJuyatAuoBmoWYFPULL2fqqYMRvmb3gt5xdWM0e4TRrxheYjPQigMSLBW4O9FvLsJ1LNJOUvKMxK7S9q+LlY4bWoRFOY2Mr5oHFSvQE1/VGx0YcZBgW4YvbnhZG95j928zh43mWxU/jqY9dPesKDQGglavZ4VdsqjgVtUb7Ij9QwoNfjH97+5k4ty/Dlt85XqxYnoCM6CCGw6d3emkJfZqVp6mF47Ngk4r4PwMJb/sq1LVifrW5iA3r7iVAygTmEbNB5SKniQsoCB1f7gtfyGMFZ8RvAfW1bTlfyJWDBUJUbRCnr48Vu1CqrDMkkFOGSrkYAg1+c3p2/5jKXRw9n/wok/9nb2Q8G3s4KS3Xp3VjkL8sgZFODIFh3pH6tZQlfb07eSR149TL0QtwaqUPteBpvMNv607Xth4l0K+bDWQN/KxXxp25MHldRkj13Hqscf0lqlb/hcxfSPXIy1v/cX9lP0T0Lfsk5epUJf0N1sGoQrK3kAHkLEoj/zHWfpn34sx038jEOOTNgkxF/ecjKB/g==
  template:
    metadata:
      name: grafana-cred-secret
      namespace: monitoring
    type: Opaque
