---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: immich-secrets
  namespace: immich
spec:
  encryptedData:
    DB_PASSWORD: AgBC6S470C/LZD1J/VKgvdvqhC62W8noQ9D2JNh69tSqWke1fPzfdBH5cXXRiXfavqE8OGKyEVS7HsdpAxn6TAQYE0vA3+rhsQG6n26G8Z8IDYFgobBrPjZZklX+DoIQTHjCdRXFkpZfej/hspU4kSf0HRW+K91yuR8d80f+jyixO/Kn0aZUoHPm5WjGZwy1ctYgdm6gqnW0U5PU2LOdVcWjs1qq7dVp0oi/20pu5LtS9NBXs6NExXQp6jjwb9Qm0RcpY2O3op4whjKDEh9M4a8h4cln3FZgGSaJZT8r/r9JD43CoSr5Wps/xpj/vQq8rYe1gnqVJOtsnXxfy4GkfUlUFF9ttohfpnJnk9kHumUz3ND3xpQoYWg2R8BOnyHDZS3LcBR4EfH4DxcZeAA0kLZxDkgoLSF/5RIJjAJE6qS9LXSaUs/o1MJPZ9hpeMPHz8RvbOaUPTf4WjTSJ2ILqVyp1BWgjkuFi91eaP8KQrnVWz2gxpoABr59OP6j0zef5wdTb6KRKqq6iQ1GPGKwVgh7xjIKN1VyGcnshaG71pJds5PFhzXGoc+cQNVwmAN5vZCSeerXFvEHQ0qPFsP3Qi+KmJg+P7SPqrldA275V3WuKFv+sCkdGZ1OQLh1fDs8vQUFnlLyD4qSGXTSe2DuQ5tftrUd8JFbnXFIZsWbquP3vVasxiZyXRF2S61+WVfVY1LeqGTtlS14qO4nVmoQd/fN
  template:
    metadata:
      name: immich-secrets
      namespace: immich
    type: Opaque
