---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: immich-secrets
  namespace: immich
spec:
  encryptedData:
    DB_PASSWORD: AgAg6nA/KN/tXDRq/Kxfn2T3mM0NzagwU91hVzmYjJeGliOQ3muPHerucMS+/Id9+x2GsBV2nTQt1MRP/8s5lsgYdCD81mAja/nSjSnI4ccV81Ifnw4RpKB2ilc63T4GUXzhGuwXry/HbqCeRvKveeDvV8A4cuglUYl/Uxv76e1dNjUU20dKWWf9k0rfpSh/NzeTeaJRpw4WhMeqC2OpKrk0cct1I3Nazd5UjT/I2K9fQbB1JrzTqrjcxVSltypkmTiqfA2tghxORJdS/c5WQ8vw0difHZbneT8pAA73siEIPT8vvLGP+RdD8ZzvnIYxxEk84I1rdDOCQXif3W/u/D9FxtrApBBw4xPZ9MFXSeSiiJ76z9OtAe7DgrDZfwj+dylfiNsdoTVwEL0XDjdCB7wIUZTJadOeEbdlyc4TAk+MYCRz1hdNpSkCaRtCh39sENGTCsqXj49dv987BemeKjN2DGDJBIHVgBWCFBfU+BGZSz+s+QVZC+/6D0pWDA049Tkf73qPhCdRsp9dIjwisMY1AeTXhPEiDmSucobBBHYTrnP+7KLj0VOblznyPYDe57Sxj0vcaXJgu121R7fEKW+5Cjc8trc0WYhtXMiuo93gpFBKCv0LEnWpG6oVCno0l254TKX8Bb9JqxIsadV1vuRkeYpgENrrI2jBQz1pdbgGy+Gh3snUEuhzIzYqA0va5DFb0OL20UqSu7vcmtY8xQyd
  template:
    metadata:
      name: immich-secrets
      namespace: immich
    type: Opaque
