services:
  coolify:
    container_name: coolify
    image: coollabsio/coolify:latest
    volumes:
      - ./.env:/var/www/html/.env:ro
      - ./data/coolify/ssh:/var/www/html/storage/app/ssh
      - ./data/coolify/databases:/var/www/html/storage/app/databases
      - ./data/coolify/backups:/var/www/html/storage/app/backups
    environment:
      - APP_ENV=production
      - PHP_MEMORY_LIMIT=256M
      - PHP_FPM_PM_CONTROL=dynamic
      - PHP_FPM_PM_START_SERVERS=1
      - PHP_FPM_PM_MIN_SPARE_SERVERS=1
      - PHP_FPM_PM_MAX_SPARE_SERVERS=10
    env_file:
      - ./.env
    ports:
      - "8000:8080"
    healthcheck:
      test: curl --fail http://127.0.0.1:8080/api/health || exit 1
      interval: 5s
      retries: 10
      timeout: 2s
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      soketi:
        condition: service_healthy
    networks:
      - coolify

  postgres:
    container_name: coolify-db
    image: postgres:17-alpine
    volumes:
      - coolify-db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "${DB_USERNAME}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_DATABASE:-coolify}"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${DB_USERNAME}",
          "-d",
          "${DB_DATABASE:-coolify}",
        ]
      interval: 5s
      retries: 10
      timeout: 2s
    networks:
      - coolify

  redis:
    container_name: coolify-redis
    image: redis:alpine
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    environment:
      REDIS_PASSWORD: "${REDIS_PASSWORD}"
    volumes:
      - coolify-redis:/data
    healthcheck:
      test: redis-cli ping
      interval: 5s
      retries: 10
      timeout: 2s
    networks:
      - coolify

  soketi:
    container_name: coolify-realtime
    image: coollabsio/coolify-realtime:latest
    ports:
      - "6001:6001"
      - "6002:6002"
    volumes:
      - ./data/coolify/ssh:/var/www/html/storage/app/ssh
    environment:
      APP_NAME: "Coolify"
      SOKETI_DEBUG: "false"
      SOKETI_DEFAULT_APP_ID: "${PUSHER_APP_ID}"
      SOKETI_DEFAULT_APP_KEY: "${PUSHER_APP_KEY}"
      SOKETI_DEFAULT_APP_SECRET: "${PUSHER_APP_SECRET}"
      SOKETI_HOST: "${SOKETI_HOST:-0.0.0.0}"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget -qO- http://127.0.0.1:6001/ready && wget -qO- http://127.0.0.1:6002/ready || exit 1",
        ]
      interval: 5s
      retries: 10
      timeout: 2s
    networks:
      - coolify

  cloudflared:
    container_name: cloudflared
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel --no-autoupdate run --token ${CLOUDFLARE_TUNNEL_TOKEN}
    networks:
      - coolify

volumes:
  coolify-db:
    name: coolify-db
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/volume/home-lab/lxc/coolify/data/coolify/db
  coolify-redis:
    name: coolify-redis
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/volume/home-lab/lxc/coolify/data/coolify/redis

networks:
  coolify:
    external: true
