apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-media-pv
spec:
  capacity:
    storage: 3.5Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nfsvers=4.2 # NFS Version
    - rsize=1048576 # Buffer 1MiB
    - wsize=1048576 # Buffer 1MiB
    - hard
    - timeo=600 # Timeout 60s
    - retrans=2 # Retries
  nfs:
    server: 192.168.10.50
    path: /mnt/mainpool/media/plex
