---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: n8n-secrets
  namespace: n8n
spec:
  encryptedData:
    N8N_ENCRYPTION_KEY: AgBCURH4A572HzWP/3xWQs26N8cZ6ykyiZO4AFy+r/1IQaSJaVekBGusq33WLe04Ug5z4yRemsCZaaTiDM+y5l2VtM+ky0mg5nsQ9wlIPYVPatsB7rIvdQFQiNYufL3dYMf1KhYwURnRlJbiserEpt3CokVmx7qZjRGDrzblc+USMbSQ+/2Vl+7rS8X66egXZIgpHsU8pesr2Pgi3qWNnPZDi3N3Y3KPrZgftL5myoC5/USezBKocaix0J+hqsbVeMlQGQ7Zb1Ua5LalZg4vFYhjouMJ4eyEkHF0rA1CAWg7PpvsZQgoRYjkaDNEVY0J3I/QrLRB22LNOMRrqQ482Q7o+Q599FnZbHof8a1LyIbhUyezRgT+p9BMGvFjV1JtjYLDPtvjiSVogu9+FtCTIPHbc4DA4/SJAKw7H/bZjen1uMMWjEG7D20RUdxvaOoix8jgXGRRx7DXGHU908FyIUDg7EkFVJivq+nB/LrhjiDHuD/+KsmOXHxDvUK6MeJyxPYt9lcM7eQ0ajjhAI4GOfILAd5yPB2bzp23h4+XOdioCaFv8cWMz0ZI1UFRpJelFw78cHgjIv3CDAJAQ5c7dfralEcBx2IHg2S9y/b3CPnOOKSJH230N53UYpXdA4gaiqAZ8MoAmcQs27p3/E6xToKWNWaHUcBlVcnvk0+fYGhlXUjxXJRToOX/pTAvpkex+kCa0QSiYB2q4YTNcMCD/ymqssckk0PvAwiNOagd2m/Cm90Pix+Aai3sF4KHYrFab14H5/fzoDyW8mREBEboFG/F
    POSTGRES_DB_PASSWORD: AgCO7El2nfPwbVc5lU/pc6pgutM8IIgv1x2Qvc3RHRKWI0BMXXzedSTYWwSCf+Coz9PNH3zFA446eviU91QaRVGxBjrkhj8XhBUK/xtliNN+mJvjkPqavESni4BSdXlaOeNutD1roCSS/2jLgKTrbNvhnroW+hicDCo8PLQzZSRpmUbkNJX3X4WIBp/3i3txP9zjrR1rjO3irLls418flmhr0bRCXtFWKoIpGIPprLuUu3TL7yj+9dbBMQtjrJSZLfqo7nXHTr8waMp2v1nOoS9LZEuZXSlobcKxr9glDTlan81/USfsqHCCtHy6NbIzf1TMEEj60HjoEOSNsMAMlG4EU3P51kaqxAhAJp46RolZ2c1/WbT4q8VVeikeTwm6rV+POsHC0usVE96FUclFw/qkXMd1Ah331N+tEfavp08SNIM7pAnddyupV12j80M62esFVjpjBXMVa4O91or1/vsmulXGe70lc9wJw8l/W6i+YLJbWHh/OURRpvAZSMXjyk+jr9Gobka5z0/jk3wL3FGhqhnn9EkyMM7fzIQFBhPWQuJk1MmL7ZX8bn2bQWdhFt0+0dkbxfuBwNKIIn+TWxib90j+uuVYysDVI3z0K9sfwbAoslqXT/Eloj1ePDpPTR340fXEDAy2xYhn0N3uWuZqcOdY86ouG7tYQb5fiEt68FkPADsHRwjcCLBQH04LsgQRUQ3ssKC/RH86+X5+vQ==
  template:
    metadata:
      name: n8n-secrets
      namespace: n8n
    type: Opaque
