containers:
  children:
    netbox_app:
      hosts:
        netbox:
          ansible_host: 192.168.10.48
          ansible_user: root
    qbittorent:
      hosts:
        qbittorent:
          ansible_host: 192.168.10.50
          ansible_user: root
