k3s_cluster:
  children:
    k3s_main_server:
    k3s_agents:

ubuntu_containers:
  children:
    k3s_api:

k3s_main_server:
  hosts:
    vm-terraform-1:
      ansible_host: 192.168.10.231

k3s_agents:
  hosts:
    vm-terraform-3:
      ansible_host: 192.168.10.233

k3s_api:
  hosts:
    k3s-database:
      ansible_host: 192.168.10.44

    k3s-proxy:
      ansible_host: 192.168.10.45
