{
 "title": "Kubernetes",
 "tags": [
  "kubernetes",
  "cluster"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(up{cluster=\"$cluster\"},cluster)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(up{metrics_path=\"/metrics\", cluster=\"$cluster\", job=\"kubelet\"},instance)"
    }
   },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(node_uname_info{job=\"node-exporter\", cluster=\"$cluster\"},instance)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_namespace_status_phase{job=\"kube-state-metrics\"},namespace)"
    }
   },
   {
    "name": "volume",
    "label": "PersistentVolumeClaim",
    "query": {
     "query": "label_values(kube_persistentvolumeclaim_info{job=\"kube-state-metrics\", namespace=\"$namespace\"},persistentvolumeclaim)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Overview (Per Instance)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Running Kubelets",
     "type": "stat",
     "gridPos": { "h": 6, "w": 2, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kubelet_node_name{cluster=\"$cluster\", job=\"kubelet\", metrics_path=\"/metrics\"})"
      }
     ]
    },
    {
     "title": "Global CPU  Usage",
     "type": "bargauge",
     "gridPos": { "h": 6, "w": 4, "x": 2, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(sum by (instance, cpu) (rate(node_cpu_seconds_total{mode!~\"idle|iowait|steal\", cluster=\"$cluster\"}[$__rate_interval])))",
       "legendFormat": "Real Linux"
      },
      {
       "expr": "avg(sum by (core) (rate(windows_cpu_time_total{mode!=\"idle\", cluster=\"$cluster\"}[$__rate_interval])))",
       "legendFormat": "Real Windows"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\", cluster=\"$cluster\"}) / sum(machine_cpu_cores{cluster=\"$cluster\"})",
       "legendFormat": "Requests"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits{resource=\"cpu\", cluster=\"$cluster\"}) / sum(machine_cpu_cores{cluster=\"$cluster\"})",
       "legendFormat": "Limits"
      }
     ]
    },
    {
     "title": "Global RAM Usage",
     "type": "bargauge",
     "gridPos": { "h": 6, "w": 4, "x": 6, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(node_memory_MemTotal_bytes{cluster=\"$cluster\"} - node_memory_MemAvailable_bytes{cluster=\"$cluster\"}) / sum(node_memory_MemTotal_bytes{cluster=\"$cluster\"})",
       "legendFormat": "Real Linux"
      },
      {
       "expr": "sum(windows_memory_available_bytes{cluster=\"$cluster\"} + windows_memory_cache_bytes{cluster=\"$cluster\"}) / sum(windows_os_visible_memory_bytes{cluster=\"$cluster\"})",
       "legendFormat": "Real Windows"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\", cluster=\"$cluster\"}) / sum(machine_memory_bytes{cluster=\"$cluster\"})",
       "legendFormat": "Requests"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits{resource=\"memory\", cluster=\"$cluster\"}) / sum(machine_memory_bytes{cluster=\"$cluster\"})",
       "legendFormat": "Limits"
      }
     ]
    },
    {
     "title": "Running Pods",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 10, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kubelet_running_pods{cluster=\"$cluster\", job=\"kubelet\", metrics_path=\"/metrics\", instance=~\"$instance\"})"
      }
     ]
    },
    {
     "title": "Non-Running Pods",
     "type": "stat",
     "gridPos": { "h": 6, "w": 3, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_status_phase{cluster=\"$cluster\", phase!=\"Running\"})"
      }
     ]
    },
    {
     "title": "Actual Volume Count",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 15, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(volume_manager_total_volumes{cluster=\"$cluster\", job=\"kubelet\", metrics_path=\"/metrics\", instance=~\"$instance\", state=\"actual_state_of_world\"})"
      }
     ]
    },
    {
     "title": "Pod Status",
     "type": "table",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
     "targets": [
      {
       "expr": "sum by (phase) (kube_pod_status_phase{cluster=\"$cluster\"})",
       "legendFormat": "{{phase}}"
      }
     ]
    },
    {
     "title": "Running Containers",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 10, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kubelet_running_containers{cluster=\"$cluster\", job=\"kubelet\", metrics_path=\"/metrics\", instance=~\"$instance\"})"
      }
     ]
    },
    {
     "title": "Desired Volume Count",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 15, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(volume_manager_total_volumes{cluster=\"$cluster\", job=\"kubelet\", metrics_path=\"/metrics\", instance=~\"$instance\",state=\"desired_state_of_world\"})"
      }
     ]
    },
    {
     "title": "Pods in CrashLoopBackOff / ImagePullBackOff",
     "type": "table",
     "gridPos": { "h": 8, "w": 9, "x": 0, "y": 7 },
     "targets": [
      {
       "expr": "kube_pod_container_status_waiting_reason{reason=~\"(CrashLoopBackOff|ImagePullBackOff)\"} > 0",
       "legendFormat": "__table"
      }
     ]
    },
    {
     "title": "Pod Restarts (last 10m)",
     "type": "table",
     "gridPos": { "h": 8, "w": 8, "x": 9, "y": 7 },
     "targets": [
      {
       "expr": "round(sum by (namespace, pod) (increase(kube_pod_container_status_restarts_total[10m])) > 0)\n",
       "legendFormat": "__table"
      }
     ]
    },
    {
     "title": "OOMKilled Containers",
     "type": "table",
     "gridPos": { "h": 8, "w": 7, "x": 17, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "count by (namespace, pod, container) (kube_pod_container_status_last_terminated_reason{reason=\"OOMKilled\"} == 1)",
       "legendFormat": "__table"
      }
     ]
    },
    {
     "title": "Operation Duration 99th quantile",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(kubelet_runtime_operations_duration_seconds_bucket{cluster=\"$cluster\",job=\"kubelet\", metrics_path=\"/metrics\",instance=~\"$instance\"}[$__rate_interval])) by (instance, operation_type, le))",
       "legendFormat": "{{instance}} {{operation_type}}"
      }
     ]
    },
    {
     "title": "Kubernetes Resource Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(kube_namespace_labels{cluster=\"$cluster\"})",
       "legendFormat": "Namespaces"
      },
      {
       "expr": "sum(kube_pod_container_status_running{cluster=\"$cluster\"})",
       "legendFormat": "Running Containers"
      },
      {
       "expr": "sum(kube_pod_status_phase{phase=\"Running\", cluster=\"$cluster\"})",
       "legendFormat": "Running Pods"
      },
      {
       "expr": "sum(kube_service_info{cluster=\"$cluster\"})",
       "legendFormat": "Services"
      },
      {
       "expr": "sum(kube_endpoint_info{cluster=\"$cluster\"})",
       "legendFormat": "Endpoints"
      },
      {
       "expr": "sum(kube_ingress_info{cluster=\"$cluster\"})",
       "legendFormat": "Ingresses"
      },
      {
       "expr": "sum(kube_deployment_labels{cluster=\"$cluster\"})",
       "legendFormat": "Deployments"
      },
      {
       "expr": "sum(kube_statefulset_labels{cluster=\"$cluster\"})",
       "legendFormat": "Statefulsets"
      },
      {
       "expr": "sum(kube_daemonset_labels{cluster=\"$cluster\"})",
       "legendFormat": "Daemonsets"
      },
      {
       "expr": "sum(kube_persistentvolumeclaim_info{cluster=\"$cluster\"})",
       "legendFormat": "Persistent Volume Claims"
      },
      {
       "expr": "sum(kube_hpa_labels{cluster=\"$cluster\"})",
       "legendFormat": "Horizontal Pod Autoscalers"
      },
      {
       "expr": "sum(kube_configmap_info{cluster=\"$cluster\"})",
       "legendFormat": "Configmaps"
      },
      {
       "expr": "sum(kube_secret_info{cluster=\"$cluster\"})",
       "legendFormat": "Secrets"
      },
      {
       "expr": "sum(kube_networkpolicy_labels{cluster=\"$cluster\"})",
       "legendFormat": "Network Policies"
      },
      {
       "expr": "count(count by (node) (kube_node_info{cluster=\"$cluster\"}))",
       "legendFormat": "Nodes"
      }
     ]
    }
   ]
  },
  {
   "title": "Per Namespace",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate5m{cluster=\"$cluster\", namespace=\"$namespace\"}) by (pod)",
       "legendFormat": "__auto"
      },
      {
       "expr": "scalar(max(kube_resourcequota{cluster=\"$cluster\", namespace=\"$namespace\", type=\"hard\",resource=\"requests.cpu\"}))",
       "legendFormat": "quota - requests"
      },
      {
       "expr": "scalar(max(kube_resourcequota{cluster=\"$cluster\", namespace=\"$namespace\", type=\"hard\",resource=\"limits.cpu\"}))",
       "legendFormat": "quota - limits"
      }
     ]
    },
    {
     "title": "Memory Usage (w/o cache)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", cluster=\"$cluster\", namespace=\"$namespace\", container!=\"\", image!=\"\"}) by (pod)",
       "legendFormat": "__auto"
      },
      {
       "expr": "scalar(max(kube_resourcequota{cluster=\"$cluster\", namespace=\"$namespace\", type=\"hard\",resource=\"requests.memory\"}))",
       "legendFormat": "quota - requests"
      },
      {
       "expr": "scalar(max(kube_resourcequota{cluster=\"$cluster\", namespace=\"$namespace\", type=\"hard\",resource=\"limits.memory\"}))",
       "legendFormat": "quota - limits"
      }
     ]
    },
    {
     "title": "CPU Quota",
     "type": "table",
     "description": "Hard limit per namespace",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "targets": [
      {
       "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate5m{cluster=\"$cluster\", namespace=\"$namespace\"}) by (pod)"
      },
      {
       "expr": "sum(cluster:namespace:pod_cpu:active:kube_pod_container_resource_requests{cluster=\"$cluster\", namespace=\"$namespace\"}) by (pod)"
      },
      {
       "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate5m{cluster=\"$cluster\", namespace=\"$namespace\"}) by (pod) / sum(cluster:namespace:pod_cpu:active:kube_pod_container_resource_requests{cluster=\"$cluster\", namespace=\"$namespace\"}) by (pod)"
      },
      {
       "expr": "sum(cluster:namespace:pod_cpu:active:kube_pod_container_resource_limits{cluster=\"$cluster\", namespace=\"$namespace\"}) by (pod)"
      },
      {
       "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate5m{cluster=\"$cluster\", namespace=\"$namespace\"}) by (pod) / sum(cluster:namespace:pod_cpu:active:kube_pod_container_resource_limits{cluster=\"$cluster\", namespace=\"$namespace\"}) by (pod)"
      }
     ]
    },
    {
     "title": "Memory Quota",
     "type": "table",
     "description": "Hard limit per namespace",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", cluster=\"$cluster\", namespace=\"$namespace\",container!=\"\", image!=\"\"}) by (pod)"
      },
      {
       "expr": "sum(cluster:namespace:pod_memory:active:kube_pod_container_resource_requests{cluster=\"$cluster\", namespace=\"$namespace\"}) by (pod)"
      },
      {
       "expr": "sum(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", cluster=\"$cluster\", namespace=\"$namespace\",container!=\"\", image!=\"\"}) by (pod) / sum(cluster:namespace:pod_memory:active:kube_pod_container_resource_requests{cluster=\"$cluster\", namespace=\"$namespace\"}) by (pod)"
      },
      {
       "expr": "sum(cluster:namespace:pod_memory:active:kube_pod_container_resource_limits{cluster=\"$cluster\", namespace=\"$namespace\"}) by (pod)"
      },
      {
       "expr": "sum(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", cluster=\"$cluster\", namespace=\"$namespace\",container!=\"\", image!=\"\"}) by (pod) / sum(cluster:namespace:pod_memory:active:kube_pod_container_resource_limits{cluster=\"$cluster\", namespace=\"$namespace\"}) by (pod)"
      },
      {
       "expr": "sum(container_memory_rss{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", cluster=\"$cluster\", namespace=\"$namespace\",container!=\"\"}) by (pod)"
      },
      {
       "expr": "sum(container_memory_cache{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", cluster=\"$cluster\", namespace=\"$namespace\",container!=\"\"}) by (pod)"
      },
      {
       "expr": "sum(container_memory_swap{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", cluster=\"$cluster\", namespace=\"$namespace\",container!=\"\"}) by (pod)"
      }
     ]
    },
    {
     "title": "Volume Space Usage",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 4, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max without(instance,node) (\n(\n  topk(1, kubelet_volume_stats_capacity_bytes{cluster=\"$cluster\", job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"$namespace\", persistentvolumeclaim=~\"$volume\"})\n  -\n  topk(1, kubelet_volume_stats_available_bytes{cluster=\"$cluster\", job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"$namespace\", persistentvolumeclaim=~\"$volume\"})\n)\n/\ntopk(1, kubelet_volume_stats_capacity_bytes{cluster=\"$cluster\", job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"$namespace\", persistentvolumeclaim=~\"$volume\"})\n* 100)\n"
      }
     ]
    },
    {
     "title": "Volume Space Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 4, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "(\n  sum without(instance, node) (\n    topk(\n      1,\n      kubelet_volume_stats_capacity_bytes{\n        cluster=~\"$cluster\",\n        job=\"kubelet\",\n        metrics_path=\"/metrics\",\n        namespace=~\"$namespace\",\n        persistentvolumeclaim=~\"${volume:regex}\"\n      }\n    )\n  )\n  -\n  sum without(instance, node) (\n    topk(\n      1,\n      kubelet_volume_stats_available_bytes{\n        cluster=~\"$cluster\",\n        job=\"kubelet\",\n        metrics_path=\"/metrics\",\n        namespace=~\"$namespace\",\n        persistentvolumeclaim=~\"${volume:regex}\"\n      }\n    )\n  )\n)\n",
       "legendFormat": "Used Space"
      },
      {
       "expr": "sum without(instance, node) (topk(1, (kubelet_volume_stats_available_bytes{cluster=\"$cluster\", job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"$namespace\", persistentvolumeclaim=~\"$volume\"})))\n",
       "legendFormat": "Free Space"
      }
     ]
    },
    {
     "title": "Top PVCs by Usage (%) – $namespace",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100 * (\n  sum by (persistentvolumeclaim) (kubelet_volume_stats_used_bytes{cluster=~\"$cluster\", job=\"kubelet\", metrics_path=\"/metrics\", namespace=~\"$namespace\"})\n  /\n  sum by (persistentvolumeclaim) (kubelet_volume_stats_capacity_bytes{cluster=~\"$cluster\", job=\"kubelet\", metrics_path=\"/metrics\", namespace=~\"$namespace\"})\n)",
       "legendFormat": "{{persistentvolumeclaim}}"
      }
     ]
    },
    {
     "title": "Receive Bandwidth",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum(rate(container_network_receive_bytes_total{cluster=\"$cluster\", namespace=\"$namespace\"}[$__rate_interval])) by (pod)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Transmit Bandwidth",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum(rate(container_network_transmit_bytes_total{cluster=\"$cluster\", namespace=\"$namespace\"}[$__rate_interval])) by (pod)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Node Exporter (Per Node)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100 -\n(\n  avg by (instance) (\n    rate(node_cpu_seconds_total{job=\"node-exporter\", instance=\"$node\", cluster=\"$cluster\", mode=\"idle\"}[5m])\n  )\n  * 100\n)\n"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100 -\n(\n  avg(node_memory_MemAvailable_bytes{job=\"node-exporter\", instance=\"$node\", cluster=\"$cluster\"}) /\n  avg(node_memory_MemTotal_bytes{job=\"node-exporter\", instance=\"$node\", cluster=\"$cluster\"})\n* 100\n)\n"
      }
     ]
    },
    {
     "title": "Load Average",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "node_load1{job=\"node-exporter\", instance=\"$node\", cluster=\"$cluster\"}",
       "legendFormat": "1m load average"
      },
      {
       "expr": "node_load5{job=\"node-exporter\", instance=\"$node\", cluster=\"$cluster\"}",
       "legendFormat": "5m load average"
      },
      {
       "expr": "node_load15{job=\"node-exporter\", instance=\"$node\", cluster=\"$cluster\"}",
       "legendFormat": "15m load average"
      },
      {
       "expr": "count(node_cpu_seconds_total{job=\"node-exporter\", instance=\"$node\", cluster=\"$cluster\", mode=\"idle\"})",
       "legendFormat": "logical cores"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "(\n  (1 - sum without (mode) (rate(node_cpu_seconds_total{job=\"node-exporter\", mode=~\"idle|iowait|steal\", instance=\"$node\", cluster=\"$cluster\"}[$__rate_interval])))\n/ ignoring(cpu) group_left\n  count without (cpu, mode) (node_cpu_seconds_total{job=\"node-exporter\", mode=\"idle\", instance=\"$node\", cluster=\"$cluster\"})\n)\n",
       "legendFormat": "{{cpu}}"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "(\n  node_memory_MemTotal_bytes{job=\"node-exporter\", instance=\"$node\", cluster=\"$cluster\"}\n-\n  node_memory_MemFree_bytes{job=\"node-exporter\", instance=\"$node\", cluster=\"$cluster\"}\n-\n  node_memory_Buffers_bytes{job=\"node-exporter\", instance=\"$node\", cluster=\"$cluster\"}\n-\n  node_memory_Cached_bytes{job=\"node-exporter\", instance=\"$node\", cluster=\"$cluster\"}\n)\n",
       "legendFormat": "memory used"
      },
      {
       "expr": "node_memory_Buffers_bytes{job=\"node-exporter\", instance=\"$node\", cluster=\"$cluster\"}",
       "legendFormat": "memory buffers"
      },
      {
       "expr": "node_memory_Cached_bytes{job=\"node-exporter\", instance=\"$node\", cluster=\"$cluster\"}",
       "legendFormat": "memory cached"
      },
      {
       "expr": "node_memory_MemFree_bytes{job=\"node-exporter\", instance=\"$node\", cluster=\"$cluster\"}",
       "legendFormat": "memory free"
      }
     ]
    },
    {
     "title": "Disk I/O",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
     "targets": [
      {
       "expr": "rate(node_disk_read_bytes_total{job=\"node-exporter\", instance=\"$node\", cluster=\"$cluster\", device=~\"(/dev/)?(mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|md.+|dasd.+)\"}[$__rate_interval])",
       "legendFormat": "{{device}} read"
      },
      {
       "expr": "rate(node_disk_written_bytes_total{job=\"node-exporter\", instance=\"$node\", cluster=\"$cluster\", device=~\"(/dev/)?(mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|md.+|dasd.+)\"}[$__rate_interval])",
       "legendFormat": "{{device}} written"
      },
      {
       "expr": "rate(node_disk_io_time_seconds_total{job=\"node-exporter\", instance=\"$node\", cluster=\"$cluster\", device=~\"(/dev/)?(mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|md.+|dasd.+)\"}[$__rate_interval])",
       "legendFormat": "{{device}} io time"
      }
     ]
    },
    {
     "title": "Disk Space Usage",
     "type": "table",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "max by (mountpoint) (node_filesystem_size_bytes{job=\"node-exporter\", instance=\"$node\", cluster=\"$cluster\", fstype!=\"\", mountpoint!=\"\"})\n"
      },
      {
       "expr": "max by (mountpoint) (node_filesystem_avail_bytes{job=\"node-exporter\", instance=\"$node\", cluster=\"$cluster\", fstype!=\"\", mountpoint!=\"\"})\n"
      }
     ]
    },
    {
     "title": "Network Received",
     "type": "timeseries",
     "description": "Network received (bits/s)",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "rate(node_network_receive_bytes_total{job=\"node-exporter\", instance=\"$node\", cluster=\"$cluster\", device!=\"lo\"}[$__rate_interval]) * 8",
       "legendFormat": "{{device}}"
      }
     ]
    },
    {
     "title": "Network Transmitted",
     "type": "timeseries",
     "description": "Network transmitted (bits/s)",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "rate(node_network_transmit_bytes_total{job=\"node-exporter\", instance=\"$node\", cluster=\"$cluster\", device!=\"lo\"}[$__rate_interval]) * 8",
       "legendFormat": "{{device}}"
      }
     ]
    }
   ]
  },
  {
   "title": "API Server",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Availability (30d) > 99.000%",
     "type": "stat",
     "description": "How many percent of requests (both read and write) in 30 days have been answered successfully and fast enough?",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "apiserver_request:availability30d{verb=\"all\", cluster=\"$cluster\"}"
      }
     ]
    },
    {
     "title": "ErrorBudget (30d) > 99.000%",
     "type": "timeseries",
     "description": "How much error budget is left looking at our 0.990% availability guarantees?",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "100 * (apiserver_request:availability30d{verb=\"all\", cluster=\"$cluster\"} - 0.990000)",
       "legendFormat": "errorbudget"
      }
     ]
    },
    {
     "title": "Read Availability (30d)",
     "type": "stat",
     "description": "How many percent of read requests (LIST,GET) in 30 days have been answered successfully and fast enough?",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "apiserver_request:availability30d{verb=\"read\", cluster=\"$cluster\"}"
      }
     ]
    },
    {
     "title": "Read SLI - Requests",
     "type": "timeseries",
     "description": "How many read requests (LIST,GET) per second do the apiservers get by code?",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by (code) (code_resource:apiserver_request_total:rate5m{verb=\"read\", cluster=\"$cluster\"})",
       "legendFormat": "{{ code }}"
      }
     ]
    },
    {
     "title": "Read SLI - Errors",
     "type": "timeseries",
     "description": "How many percent of read requests (LIST,GET) per second are returned with errors (5xx)?",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum by (resource) (code_resource:apiserver_request_total:rate5m{verb=\"read\",code=~\"5..\", cluster=\"$cluster\"}) / sum by (resource) (code_resource:apiserver_request_total:rate5m{verb=\"read\", cluster=\"$cluster\"})",
       "legendFormat": "{{ resource }}"
      }
     ]
    },
    {
     "title": "Write Availability (30d)",
     "type": "stat",
     "description": "How many percent of write requests (POST|PUT|PATCH|DELETE) in 30 days have been answered successfully and fast enough?",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "apiserver_request:availability30d{verb=\"write\", cluster=\"$cluster\"}"
      }
     ]
    },
    {
     "title": "Write SLI - Requests",
     "type": "timeseries",
     "description": "How many write requests (POST|PUT|PATCH|DELETE) per second do the apiservers get by code?",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by (code) (code_resource:apiserver_request_total:rate5m{verb=\"write\", cluster=\"$cluster\"})",
       "legendFormat": "{{ code }}"
      }
     ]
    },
    {
     "title": "Write SLI - Errors",
     "type": "timeseries",
     "description": "How many percent of write requests (POST|PUT|PATCH|DELETE) per second are returned with errors (5xx)?",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum by (resource) (code_resource:apiserver_request_total:rate5m{verb=\"write\",code=~\"5..\", cluster=\"$cluster\"}) / sum by (resource) (code_resource:apiserver_request_total:rate5m{verb=\"write\", cluster=\"$cluster\"})",
       "legendFormat": "{{ resource }}"
      }
     ]
    }
   ]
  }
 ]
}