---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: indexer-cred
  namespace: wazuh
spec:
  encryptedData:
    password: AgCPKIXnEaRvHF6c7LhwYNn8/7vzyX8Gu75z/tvS/jrDePYMsw/U4oJuAAwymrRxi3+sTQO/8DcsATkZiaIiD9JrQUJX4P8iIczjZNIlKuaa9doJ7AeqOQqAtS2hlnUnKiwpcnmDCh1InibRGYvI4aOZqmjZU8vqlnvRhnXpS67Yey9N8nqQkb0kLiEzwBhDWI9FV7B/+2EqT8Xuf7pzfYZx+qZmiedK2sHcz3WBeG4GNHvpk7L+fzJAUmedBVcxfedunTX0t8eiul4XPY1kFppICT31m6w4QTdfmu3xQm66encXQPuGymorpBBAuY8balS6Jbpci9WfQfzSXs1s08SkfvUDSqyvbjf6RSjuaXLd8AntB3DFVRIowy1vmMORgCjCDbMGE3IMIj3Fm11A89UCzAU8pDQy6CcRb5Zu/5ZSlOXRTjqtra+5jKJ6jE5LAnnF4MlFqzTrQfC3GrusG7fuTXIxVWrCXDtl2hqunUP4mgPd53Xd0nxJrxp111jF4X3cy77yMp6PnDyim+ay4ud+KkeL4UC9a2oWwzOh1FXMoOwtU5nchb79mgwgKRcZ5NF4/BiwdUkEbFa970PwRTfLJOXwlvJ9yfQ7v+fcr+5eKmAb0XfBKo/LL9B2ZSAL/DWHQ14TkAvSDmBPXDFkCmyk4pibw/HTpi9Zv4z5zbd94+qXngRCiQZYlavhcU0SvXSRf3csvgIIND1pj809HA==
    username: AgCHi5Xn6RXimRpe50/5Mn7jRVOwSNcn4xcpGqtsaWCIRNRMUCoN2soJ/EonfojR3+2eQEgBjgBG2yEFvifdpEsDnlUFle5af1+MhcSMlt83KBCFizyKarMSNsrbIJrPDDSEhT9WjQ0F7iRRlY6eqUoXUEeMJkwz2o4yctpJpioeujmrpgt431szmYDEJzVD8GNdZdpS6Um5HyvS3hOqmYE4Jzy31ipkDRsLfCSqzCNu2+Fg3b/qLqjpaZo2MrwtN9vTV7GLBo9HCqVtD4RxH4Mbx1Wgy7v/X+DNUXNmDLZoYyjeoZNT6CBxr6W4x+piePRDrSb5TNirVvCwN4nyXh3ju+uhJnW3qNOoEMVb0wFRCenE7orOfJd81LW6KGfOjCSOsb199tHF/OcJQkR86CUWgGFyh6f+koNfroybp2A0CD6HHpf9VWqNX93JvRsxEsNxVlQ/vPQmtaZ1N+PX6WmmYdkrzipri3GarEV8VQqlYLqTD7agcSHY2Gt8+fdhO4iNGm0GzvqnxT4AbyOSplfZwpsq5AjjrbYSVEQ0oEkxOsjn+FIBbEJ5SaRiegDLlctewoPtkOvrDv1Aw4LF+MvA0nyC1EIOuCtzZRVfOzObYuvqGgLdFpvuMYkURF7l6XKs18LffW7RSbThotpdcxJsElDU0KpoTS6+tTng21DYxmw0B7teBYOpyNZxTwc1iWllywMaLA==
  template:
    metadata:
      name: indexer-cred
      namespace: wazuh
    type: Opaque
