---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: wazuh-api-cred
  namespace: wazuh
spec:
  encryptedData:
    password: AgDXf2afMA/BIDeJ/OugEO5+jdFup6R2elBWapECIHkkMWcV4k74EUQ421MI7texGJpi2l7lZ12ZhnTkHVTha2ZO5tNbqRAqbJXJj9mxNIXl+jI9vXpe0oCLtjqLY/t8qXp8TglRa74j3jmaMtlwKKi5sgVSkmDezin99OdmvwnvZPRomOxozJCOhgyQtvrq4sH0GBQLkxJAWga29ACRTAtAfIUPLUf+qWoLilxgKBTniDOg43egWpe2NG+E0+SSfqg78OR0/+a8Jyhj+f5ILSuhJBteeg03rMAQRV3VmYST2cM2Y7fvzLGhd9sVRKfim6ztff5pI3VF2XWvsLf/9IN94iFz8LrH9zUZJXITCtIvVtCuXQi7F/7XaRHtgNodImQGRmEv3p2kSSEIV4nhm0Kmoeys38ABfofz1PwOFgvjB8N0hEb6//YzwJp/i59CIPbrEFI21rYFVINg0Cb6zx39wgHbQpqhDjDfO+Yin3h77yGXio8T/2oU1qEssVTTq3iES7/kvfjwOH7ske3pX2pVgxXQf5qHAF8Wd3ZGuC8h0ZGdJmjkuBKA2eYq3SfYt7F6kMXru4XfdVQAZkmvcDuwZsUEgPnxB3H7fFNc7RYLbkCisKyRjFI4p3VPot7EWeuxl2/Crt1mzeBl2RHCG8A43PHctokE8SbGq/ZYdirl1EQxUvGBWQs9XFntAw3gkWSxG2BBFQYIgqqLa9ejqndw1lLbqw==
    username: AgDUAuwOYaswJcK+YvGScEX78dE7sJC+cRo3qpQlXQB3iix4tuDvZrT/CylVVeFXPZltzQMvubXV57txWiNqmgZ89sDH0tEev/Vd95woNlfGff8zmppcOynnK1Ywi8NApki6bVuY9c3lR7T9Ssu/fCN3dKVrOjGZqLg3nLt6+3ihyt+C5XBitC0zTiR+p7b3+RinrV8FGfCjnY4fSa8XSc5ySdRNySfpN/mZfEKy62BOArbzed+m4JCR+FkykqO9Cs9+BF1UOfTWIRfyGrUKShM89W32Qw3VGAUdVY5FqDhPF8nj7EiBqoOlT8oyJiSBynXoOq78czzCkpQCUInUasL+CFV/UNPEieiX1/6juR/FYT4j7r6nO+Q/PZrYkE31aOn/bixr3Zs5zKs1gFMgbEoUmB01toGEgY5XWRnIJdUxArBQfmXkqJYGLC8mymzSyjqB4wduq9GYxQg2YVwp2epdqcrshRUr0A99o6vMHYGfg8iWLF71MTSiq9FJU7uHzKaHz4SIlEhE8NbnNhwtClWvanTxIhSFdQm00ZdyqELH8JxNW9wq0ka7JVCwyYEZFyC3O3M8dL0W8eX0zxYjEXNZE4KJqbTfGEag2MXmGTjVyKvIo5yUKg2v7YchZObv24srPGJHBV9+ie6eOxux7Aklf6K67xxJcK6yUrqStt7HYDHW9CCYmD2+Kxi5ZEH1gHtKs9bQyLyYVXs=
  template:
    metadata:
      name: wazuh-api-cred
      namespace: wazuh
    type: Opaque
