---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: wazuh-api-cred
  namespace: wazuh
spec:
  encryptedData:
    password: AgANYNgpJ7/kYj9GTB8COEZ4hKN3lROCdO5HKkunTRxb2a0AZoaY6Z+C2dfufEJDNF8sV0I4naH/Ei9jAPDrfD4226TyNOrTOtjeKQjbgmQWyrTNi+q+PpwirRtO/yvGbcExWmY01Ix2IgsjMX8z7sTXlJTGaVBTOKRmS2pAU2sPhjZ40+xLlbLs/Mn93lUngY0wSrpJK+IaTYi88SNOV46pJBIcJrfrz5cWuw6T2Ur5JZ4i2rcBDn1y1NMSHsyERsD3OjhTyQSwVkRE323pmuNwvFejHmVgM9l+RDSDxz6u0fDwr5EXmWeSV0VT9UDjen0OlviZo5KRo2CpLqk95EKjo4tFgjCR7DuteFPc2emu4+mr7Om7jPiEsWnRCZU4Cnp7f4K2mPCANtB5+ImCEh4AhtX0hsYXywAiPVJWPSSGuu66TeJPdRy1oYyOH0NMEB62zD1To4QxdRDrl3m6WRSc9B9rbz+lnS/BKjCfVgW45rerF1PrS/9+K+5oQeeSJrabW1O5KADd7GuIPKQFORqZ7PsRXrUXAA9Q1eXzfrGvasLvUxqAx6TXWBocOKpigILztKXUjuaiPjXMil88h0h2KOa8/mAWir5Nkbk6u9WGePx7CwLQvfZZNFS58SsNfUGeHeNhfebAF6CohxP6wv7y74MKOzXq2Q1VU8U/XsM30iFnqRcjelX5R6/m1OGQVBlFODrmNZShS3J/fFtmTTZg8NnjFg==
    username: AgBiBu9ATWvE03kmf/qodvWgzYhrUHiXSMVRpfwmN4mI/Rk9xUjQzatTU6tvDDL8WJTNDU/G8VhvQrovRwOHOFWinhOUH1lnUbivWb0qPceuFOUHuU+gRrruGVKTk2MFfB4sbrEylpMBNBubpP/QYSEHQ7qSa3rp4luAM2/1spIgcar9iNLk6OaDIb6J6z8wSdrPbY/ZMnT2UNLD/RXeuoigBUzCRzDsdVLSYyAS9MmA+QzaHBIsvXc1+cxmwGCVvP/OTY655D1F8NGaENJCy6sbcaNUs8h6YdHx37+FC4i37GfdeQkAWsRMW5Mji0Jk2pBhQT+X1Hd7vFpBL4SGNNlAcf6+v3MWD73MMKzx3Msa1As/ZllQtV3hO2/NnNwSa668tmLwSQhql+oOyggU9fdTf1OmRxrp0DhU12LwZ9OuFsu4dMxxht8XxsV6uS+gJPRdyWKp+9KGXsUrF0peA2ckNm32jmV17ishhXM4Y+wxdp7MBNyZxIN5prGr66x42R7pr2b8fhyXhz79GF5lHTEMPGFCvZIhzmqGupWBrWPqILKuCdSIbKPe0Bl42+a3AAl1vw/M5N0xkdlyAq9haC265vAobhWTlcHAxkMdfj8CfwISVkrW1hB27F2oniI3asbp4u1FZkX7cX5b+UN2VYwekAbnqYT1udccLXllb9hgUTtxuX8MQ4rjeGI47sSyl5FNQa20UT7IQWw=
  template:
    metadata:
      name: wazuh-api-cred
      namespace: wazuh
    type: Opaque
