---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: wazuh-cluster-key
  namespace: wazuh
spec:
  encryptedData:
    key: AgCFDleVChgkJCnTbKXgOeGWiUkIKXggERNWsRJr9yccqdwdeEy3Xor8y21HT4gSx6yFHhk+XLyhNwY05jLeYctlk6qco37WomqOuuKhS+pU0+ecHSW+A32cMnVAeZE3YLelMk7Iv0TU87/I7PZdJbF23snmS2gVZ2tiUIwKMycCe6zCv7qPMh28DblGYPE4aBHgCTSIWL0G0yyMnlQyTnk0naMEfcti/wCXpNfjEYrJ0QyK9RM6GkzaL1WBoJDa+eQKLvtvJeUv3VSmq586COiKrlnBbWbfz8kP+x3UdiKHvRW/LWLzspaTDmmec8QGLizo0IWcDr090e3tzRkz7e8BD9bR8TeB1cPP6zmc7t5q5zfpY/V+wdbzBUL8xv9YZ3sS/JRSNpuh3OjiZ0iD+JmxU6vbnZbrKgLRI41cu34iboQbHITVksVUniUcIbMnAh5H4X5hkEkj83MMDELG5Q0PJcngO/hZsY8VSVZWtHkYCfH9bGf7MY43bISYytQxyFdaFkt3KKw/pEevgdOs5IRUZJfyNLMx/LR/pvb+CcyLGGNWs/69B0844RbYk5s6oVZnKzs6ww2vBT8rS2/osmkHcHnlGZrTyDpoBmV6yuVzL2WEKBotVqoNHNEkbPvoy8dzs2FM1ssl6QtD8GoF7NRPHrAE9L2X6Ym6QKbI917hEtrfQg+XGPnhxQWZpWFvsV6ttpVuX5vCCCxVDmKsYqgdNpBqo/HpeXfV3m1gJT4nIA==
  template:
    metadata:
      name: wazuh-cluster-key
      namespace: wazuh
    type: Opaque
