---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: wazuh-authd-pass
  namespace: wazuh
spec:
  encryptedData:
    authd.pass: AgCtvAVMK+kEV4r19fkR031X08aanG2t+MZ2i+2H/a0oZzktPJJuJCfyB5qWzctIoK3vg9ZIksk0WGs9xksGhAJ8cQ8oOAVSIsirDx/mca/V15Dbz10F7zrpU2/nPpPaCutRXB8pcJaXgQpvJZDMcZIEumbJoQeo1I+f7sjU/iy5mLGFTp89m+Hn4W3z2CDEE8dvDRPpTDU7m+AF61ZjH9GyuJWodLa7z9AzScOsUYTiN3+ZjOIJpf0fA1Lv9wm037u3daC1iYZ2bS63OO6ZiV2gvnb44P3NwXPQpDDayXEwkKVYFTPLhuAwQweoXhmL9pQM4XbmZEzDvjWr6pwKw6kJWo9kFkt+GyBgWDRSNzjEUiiuumL/VA497khbNiTjDTdDBNk2UEZIhmTMKu2LzKCQo2IIoCGxywK9ktb+ffWIGk6wVw4YoA7qOPplN1vx5Jl5Bu4k5keU10VySVXPlqxvJSGmCrIpNMZR7H1vGQq7prIdyZdbHlABIXj0Ne+gaQnWeqguB2aTy2IYF19iCdQu9Z4hhRY/ox9jHw/+nrbc8PSIOImFe7xy7r24GlMPaAhgKLt2RhpGu5GPE6yOXfY614MffuFQnEa3Ae5uiC0dGftNA1jGaLi4GIKoyOAKGf4aVjWrkC9RMMf0UNlc3yDB8R+g/6GkRb/xMWjorI/1hXBbvQNMTKW9/0WVzmexat1V98MeexUsPLTnguU5tHiyAY+ePQ==
  template:
    metadata:
      name: wazuh-authd-pass
      namespace: wazuh
    type: Opaque
