apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-library-nfs-pvc
  namespace: immich
  labels:
    app: immich-server 
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3.5Ti
  volumeName: immich-library-nfs-pv