services:
  pihole:
    container_name: pihole
    image: "pihole/pihole:latest"
    ports:
      # DNS Ports
      - "53:53/tcp"
      - "53:53/udp"

      # Default HTTP Port
      - "8081:80/tcp"

      # Default HTTPS Port. FTL will generate a self-signed certificate
      # - "443:443/tcp"

      # Uncomment the below if using Pi-hole as your DHCP Server
      # - "67:67/udp"

    # Volumes store your data betrweern container upgrades
    volumes:
      # For persisting Pi-hole's databases and common configuration file
      - "./pihole/etc-pihole:/etc/pihole"
    environment:
      # Set the appropriate timezone for your location
      TZ: ${TZ}

      # Set a password to access the web interfaces
      FTLCONF_webserver_api_password: ${PIHOLE_PASSWORD}

      # If using Docker's default `bridge` network setting the dns listening mode should be set to 'all'
      FTLCONF_dns_listeningMode: 'all'
      FTLCONF_dns_upstreams: "unbound#53"
    #cap_add:
    # See https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    # Required if you are using Pi-hole as your DHCP server, else not needed
    # - NET_ADMIN
    restart: unless-stopped
    networks:
      - dns_pihole_net
      - npm_network

  unbound:
    container_name: unbound
    build:
      context: ./unbound
    image: custom-unbound:latest
    volumes:
      - "./unbound/unbound.conf:/etc/unbound/unbound.conf:ro"
    restart: unless-stopped
    networks:
      - dns_pihole_net

networks:
  dns_pihole_net:
    name: dns_pihole_net
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24
  npm_network:
    external: true
