services:
  prometheus:
    container_name: prometheus
    image: "prom/prometheus:latest"
    restart: unless-stopped
    ports:
      - "9090:9090"
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    volumes:
      - "./prometheus/:/etc/prometheus"
      - "prometheus_data:/prometheus"
    env_file:
      - .env
    networks:
      - monitoring

  grafana:
    container_name: grafana
    image: "grafana/grafana-oss"
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      # Set configuration for Grafana provisioning
      - "./grafana/config/grafana.ini:/etc/grafana/grafana.ini"
      - "./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources"
      - "./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards"
      - "./grafana/provisioning/alerting/:/etc/grafana/provisioning/alerting"
      - "grafana_data:/var/lib/grafana"
    networks:
      - monitoring

  pve-exporter:
    container_name: pve-exporter
    image: "prompve/prometheus-pve-exporter:latest"
    restart: unless-stopped
    ports:
      - "9221:9221"
    volumes:
      - "./pve-exporter/pve.yml:/etc/prometheus/pve.yml"
    networks:
      - monitoring


volumes:
  prometheus_data:
  grafana_data:

networks:
  monitoring: