- name: System Hardening
  hosts: hardening-test-vm
  become: true

  tasks:
    - import_tasks: tasks/packages.yaml
    - import_tasks: tasks/daemons.yaml
    - import_tasks: tasks/kernel_modules.yaml
    - import_tasks: tasks/sudo.yaml
    - import_tasks: tasks/log_suspicious_packets.yaml
    - import_tasks: tasks/bootloader.yaml
    - import_tasks: tasks/audit-logging-rules.yaml
    - import_tasks: tasks/shell-tmout.yaml
    - import_tasks: tasks/ssh-config.yaml
