---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-secrets
  namespace: databases
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgC4Y7JcOJ7rdsSDrwL2SLj3KGuB+o+VL2+MyJguGI9Ab/xqX27Oy19hbrbrFuNXDOmhRKWgqXsHHEvCv5Uhl+srw3tAPgsPo1o9Civz2LATs6Tj3CSQd7ISjhqqJJEhLQBYf+c+XMMMDUPFpMn9G5UwJWuacR/jPE8XoKVPhcUjeNnwuiE7gHy57Wk/z/Wv1mxrZNDxjpn9XwuHxJGQSM+nuCVm+KV0q/6Cwb+weXpbt7aErOKLBkvXXTi/G+gpg1/iU5EdZ9EnSxSb6/2w+sGgTpzIPxVj+pI5Srqptwd0apvhC67+RO+0pxl+Hzb2+S4bt1YrY7GS//mUcOmMgitI6++wLcBZi1/bo81/kOWvNBfMxaoDl3WpJnxVw5GAaZ0RJTIzV5Zc6E+VAER+oEH3RCJPwVxloiLLL91/WMQvrYUrS17R37rZbi7YgNXC9fQj0/Bcp/fPHUWkf7IDlw1B6JH5TSJbvJ/ej5TFWIzpNNYICcsAb3a694jWf47lPsS0SxPUR8xkERwnh1HYOjSWSKkPNvAKucqqj8RwWCqH+rauTOVKHdlcJ+wgpAdNwF0IVmK5AW9n0BkeKEZjpXQOa33hST9n85CLCB+OG2xbHhDiljEcpF5eUabeVi0VdETcsvuejPmvQF4XCGuKtV0iGteVdYGqd1LkZtRAKBDf/B3OB6NgapgkNgNbI3LIBl6ZaOTjUyPiJOcAzNZD1g==
  template:
    metadata:
      name: postgres-secrets
      namespace: databases
    type: Opaque
