---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-secrets
  namespace: databases
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgAeRvcxdFxOg3Q50AbMrQzuMqdS2rZPzpuUjdK9Cu20/sC0jGN5D4CadwpR7sgrMgyStxGvnzOH9hE0UQ1rEpZbcXUL6sR6zI/1ggP/eDSA8YlhT7LkX7M0mjeQDu4cepp3rURf3WqHE5k4cDEQ5Pb71+sqkSqsF5Z61N5v2PiFKoHGBsvys+ikFYfXWSh3Jx3PR3VjYEZ17FaC0dFIjbRT8WtlBdRprKSNbnnt2SHcS7tmlnjzBLGJwDKBOk1TxM1LH3asqBqL3ZPD1AtZZLiqCODjNmy9adJKoqJqRvO+D4uSunNC1qRc8efx7/zzzEXtmWzR+KGA7EhTFHmOut7s8/9DSPt9aEVJUOXVxblDjrP6li7jvheMeHaOcQvlO+gP9BGb6+5tXCLedvqHozgvmloANpRNg05esqngrlD8jXJsCj4iktCTJUWt5V+UhW2oLxeAk7xQMkb8gg0WeRHHWkhhF0D6uKlg8cIBXLWcyHvy0mPInCWpXCW8USsKek1wo61nBvluAg7EsPirb2Li2xZFhKHuzaAmt5KtcvbLxvZlhYy/nk5TZu2K3297ngkH6BZd0qAUak64jJkTIlwgNL+M1SwRMzyCogaTxVbf1WRAvYDfsWzELjrlcLlO37fDfXBWtgXHN3qnEg86FKR8NCsm1ZNvmmDpMeQvK1+Kpu9gT81t/j+e1i+tO2f7IfkShdIZRLCMeEqaan5Y/w==
  template:
    metadata:
      name: postgres-secrets
      namespace: databases
    type: Opaque
