apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
data:
  url: https://argocd.poolnode.net
  oidc.config: |
    name: Authentik
    issuer: https://authentik.poolnode.net/application/o/argo-cd/
    clientID: EjYMHoT4u9UDhGpfnwpQsA0k4idmXmK7k6NaV9Hj
    clientSecret: $oidc.authentik.clientSecret
    requestedScopes:
      - openid
      - profile
      - email
      - groups
