---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-secret
  namespace: argocd
spec:
  encryptedData:
    oidc.authentik.clientSecret: AgAWly/JH1WLk7eWqA2nqvlHYPFYlvrad0BsWR3IvbME8vIRuwaDPVwHrwq4zWMWREDK5QAApqdEHac6s10E1KvbGiq+xFPokXb9gCjsS2xkgsk0xQ45bo/ZFUAOhoDMxQzqVKvbA2jTSVid8+dFBl1mT1xow7KSe1uSQSIPyoi2DPrNC0B8lVB9ntH72TkMeDtbT54Jrmr1vXr1zp83nDIO81n+GyHHJmtqX53oGOnaRytcjIsYYW+5RKbvRsaiDUse5dNfQJUcpCwJbBTYemI0xtmo0Zv4nUmLMy+TRF69M7LRAufwRHvWMNi3M0tqmFoPZ9lM1ocrv6nK+60wafhHvnxH8OE2w/c0nbEQPhxIWH4MwuZhKsoKprOnU7Zh0vawBflnn8MIXmwhRhtJd6QPfwiZd/SQNRbAf58Mo/LrBcG9XqJAeKyN16h0XkUPP6vwar2F/viKTP/kaFLK3jS8kJqsaHTjJvj+Vr8OchUkenhip9F4D7kcX43q0TGGAJGLH5PbldPdNt8CsFlVZpA2w/LIkMbhy2G7b6909QxI+511Ms/K5oF2f3diY4Lqc9XiBjSC7m0rVi1/siwTBFWsFnRL5NcmATtV0Vtwv9U6z5zlwZNiqPGQ3Ke+fj7ThckL6tJuLg6CrHA1Fj+Aq1gzHGQVkicj+04mRPAw67punhW2ZeKa+HBfI36JpkKy6JFOKOM1nZiNGneVQQu4IqcZXCCSj06nNjJ06q8yncMY/n473UoKbKIDB9cav1skxAuaKQMdB2RcaJGzkJHpKNHzAVuqgRFNUv6CGK2qGtjIRrHiIhvSKOm0vDAVuyrhB1t7BHLOe8u/nc/s4EwV+TSSfdJEg7xIyH3HxcTA2/c+Lg==
  template:
    metadata:
      name: argocd-secret
      namespace: argocd
    type: Opaque
