apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-of-apps
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  source:
    path: k3s/infra/argocd/infra
    repoURL: https://github.com/manos-grigorakis/home-lab.git
    targetRevision: main
    directory:
      recurse: true
  sources: []
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
