apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

configMapGenerator:
  - name: argocd-cmd-params-cm
    behavior: merge
    literals:
      - server.insecure=true

resources:
  - argocd-ns.yaml
  - https://raw.githubusercontent.com/argoproj/argo-cd/v3.1.8/manifests/install.yaml
  - github-repo-secret.yaml
  - ingress-route.yaml