apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    service:
      enabled: true
      type: LoadBalancer
      annotations:
        metallb.io/loadBalancerIPs: "192.168.10.120"
    api:
      dashboard: true
      insecure: false
    ports:
      web:
        forwardedHeaders:
          trustedIPs:
            - 10.0.0.0/8
            - 192.168.0.0/16
      websecure:
        forwardedHeaders:
          trustedIPs:
            - 10.0.0.0/8
            - 192.168.0.0/16
