---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: alertmanager-smtp
  namespace: monitoring
spec:
  encryptedData:
    SMTP_PASSWORD: AgBra8TP7Mq11AWUCTgI1pRy/GhSVtlo3sWQVHTjBaGXjaMeFGtdL5E9uHodHuUX3AUIbb73VltNibGJL6RX8m+UjSnDKFlz20VneBCihQj0htOv5pZ70fNVswc3v1NOEn2MZOdqfT8aav2KyNW28XQav5TAZ+R9mxdz3gZM/Jc9yH+ekxRlFtSogIEb14myx2pC8zMs5dmtHuHc+8p7Bs22ogJjSDtTlcR8pqS2cNlxhI9cJ4zty25arNhsNWc0XWwEKK235dcBRR4PIr2CRFipij152s0kamWm/2wqEuqwAG0MimcgXf/Pw2eEuS5Km46HtK0z4RJx/2CDmqqjAITCATzwrKHVJNRpDhq7trw3rniqKt2WcLPryBXSxs+T/mijUugdUt9rdg+T1R5YVzmf59cVGCfsiApndhL7CMbgcjS5QWL8j14aCj1bxGUfXjN9WbYZB8t8AgktL4Lp8II437IdMUOk74M2VO3FOhmmbWKBJfh/uJ2iexkwUkIrh5emvw5WcsejVHwZ4nLxCj1pL1W5xtePbpxa2EaCuhpYXJIkAhnIonMnxQgo90O3Xa1F8pdYLF4fRbyRItF3XOS+g0O0hQGs0Vfby9Tp/r8uqn5uA5RbuzP3+nqgt5J9zR6qttRvEYs40dNzf/M35kjpQM1uDG5vshwsyaqGv3p4pPF/k3XOgLdTkd8ctNGU8s3Ak1OWZ2J249DR7S+obQzfMhBCNg==
  template:
    metadata:
      name: alertmanager-smtp
      namespace: monitoring
    type: Opaque
