---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-secret
  namespace: argocd
spec:
  encryptedData:
    oidc.authentik.clientSecret: AgBdNycWlZ53JEJ32ELSuxCKfhFh15WSWhdJLt/feLGTVMHWT7XQLX+jxjqTVkE4J5H/oejVzflXw19K/XuAGxK2n7gL08+rhnriAfQdKIX4/myTXrOcdofXcrzgGWpVSiI29bpLpvdro7d2d6ahHXp7Op+/T96jh9Qs+3ODUPqkgBaHHQuJVoAiS7pHRix4Q80P4uX008ODkDKqM9yfhQ627vFKEUhvfzUPOfWm0LlAcNKHV6NqhEvYb8NStL42f4WNFLCDhPWXNQHPM6TqDUZ4Pvhc3CdxgL48UMUzNM1JZSsVT0UwefIYC2NalDCYJrDgjjJSYkFYL5gnrfgxKVkItFnlkGkUZAJ50JOy3cAFZoX2Z8GQaAYCxA6WPpaMB7Ntx8JKNX17i/Yydg/ZnUKfPjV5gbtB8/MttiY5v+2OHDl0UBQ4yUwfEeYg/A7/AiarOVJKoUsruKjYCLrn2Q8zjq3dDRBBsfixkAxOawIeHJqRt/WdsiS2q+XEsyZ8ArDfk/F8Hu3xw6Y+SjOx89RPcFur/gPuJdVIWD0hE7sI2Ls2FVC25m6q6EF3uc18fbTjUuudAfROvE/340oHbZSf3HRhIOxH9H6m0Mbhxlg5MNRJgrZUk/SIqRuMCR1yahlI/ZhwJkHJswt2jzSDMXL+JxN6xuc8tBdhTtKcveCSxVD/i2Fmjmo0l2JlZwcJxWcVuFWpjEwlRVib0cxqqv9xRgryLk67keAWoTwhr0FtS50KzBl7xDr+lbC3zETiDQwOCQFP3EJiYfeNiQNlNKa0rSItoGsLqLvO7O5YhlokH9HcubrU4udPEb6drOuxtonYJJ4XzKBPJLmZlHUU/gZ5HSU6PZha5TY6CeP4rVGevg==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      name: argocd-secret
      namespace: argocd
    type: Opaque
