---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-secret
  namespace: argocd
spec:
  encryptedData:
    oidc.authentik.clientSecret: AgAcVXHS+LB0/UCV6iMShhkiKgPqWm9VrnA/DBcqGGuJ0zNB9A5pEbUBdB9/cwSg6wD2y+TUTdXsxNaR2sl8pA1kgjxCcIojIbPj2xyWmSFKYfwA+KXbDt7y6G8c+AafHY7GdkkwIQkefEDEqnzJebLPIYQ4KfmVBpiSi/Srnzipvl3pERcoMCQJL3iNjXgUuQVqlbRLSHv2tch8m3WsA4tu7De1Nu03QKYMU0UBX8a7ZMOSqQH6LfUV+KtY/MOauJVi+SPg9wPx0coejotHGnbCqv6S+E2W7dYBv/Mn0EtilWMIGpQ2ERYUF7630aMPE7Mh9Fg6y7uV0VRyparKSsghmUH2WEiE9457AE74zspfXLl+31zMdAvTAaNsuRwiLxlFN9FTKBb1gN8fK9H3RHuGjCdywMLToq6KdTGVqAVt2586g/Hk/SnnR0jPFK0fR/JBZxxHL6A1n3Ho1sQXsOE51XEBOotN1D0fERN6gFmGTs59+uLfRfyVTbHJJ2MtI/elHCRaDGvI+fYJXUzO0ufU+Dw74O5OjkGIzgniNd77uv7f8YMrcctOQmKY3gNIYmDmuu0pxvXOWEyYXPazTu6B5Ad7A+GgLzNCn901GzwWMlaZm+ZzcjcY6ebDOuBRAnJ1fSKNDEJTsIht9xhtD5OSKU8VGrE+xxjMrUKkFbKOreiTbM8brhm31DPr963PSfCC+faAmI2U/DTE3pE+lqiaHQ+hEFr4mHCb/dGVWv0ODhYWmDlfAfksf+bUbsPRP9s1xyTekBlMkGzQGeqNtml7k/32Q1Vp+UlQ5me8RhzKMI+TiGyHrqbAr63eDK4aufnlql12EL0HRDAee+TFyEpSeLlncEQqsUJcV5JADUrrsA==
    server.secretkey: AgCla1RFthvHdPbz6alauAk1a5swJbGfIoh5X1wpXWgikzfZcBrNO5dPGzK3gsuOYrkjoLifbEj/H0rM+OASCHj+6izw/nQSPc4ICbmrrm5yvfwDIvIajKbSUwcVWwHjT2Swoq9TEYI5FnMTY3M2FeFNS7GiiBm81IscPWxXccCyo3VSN2rE8SqQHjMlY+enRbfNurqxm6XzW2uW16bG6RyrMEmYLiscD/Ai7anlyOl4pM1uVz67KMz6SLNauCUkukxYrC/wgB8nBEkPnP45++Yy4NIp3pYo+VSWpNPJzY3oaZAPTy0Acj97n16/pAiTQ7yAlGaVkfJ8k7Eqwd/RcvyAre6sI+aDWXxGTWui6OfaeTd0rwIVRPT7OAT409epVxJ6SV7iH8XbzxTX9g5GcCFq+IrHFDD/z21eYAKYYStu/NfQvO6Kj0kBvtMiEXr4Itfeitutq+tX5f7wMOrZu83n2NqVuGUBbhyOwouOz60HtY36SQi0L9iec6OUHLM9GbFxIEhYa+FMENKgrCxwAwAC+I2aqzFe/jwpnheHct5htCcMM6hQMsxTPa8sUKWmoL5RGgb+9kDJe7ZqzU7v3EAKZUNGDO6Bc3B8FIxWzrFd7TYqjCDmiJ9zKlsDTmE7mjh8qNGSkoQinQVG02xBF7odQGUPkcXPv6aYcTd8fxc2CDvLGFIAaP/IJ9u1P1UGwoFVGhfWdw/I4TfJr6i+3/lBlSJH9laoJtSyRnbZGYfKyG1dJAuJ8R0W2QosFA==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      name: argocd-secret
      namespace: argocd
    type: Opaque
