---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-secret
  namespace: argocd
spec:
  encryptedData:
    oidc.authentik.clientSecret: AgAe8p2RUBosTzPUO74rGj5AKqfzK0cKx7EzGMD8twkZTeQ61rc0Tfdh3wZKb1UTrBE40JDf4H1F5Bkapx2lFt4QewtjgKmdo99nDZu1fSEyaNAswxfKfykV1HP/Dp9fvUULS+ZBSHnWOVu0nakdZQvKgzuJIJO7Ky5fn9pcIW/eKlWyyKFaRexxb5wUy3FwX2PoOQkrZ9bbwFPRXsk92OA3RqZTAWp/tnrAEsxLnPtkMzBS2mrqqpT6HqkopvaQFQdlyVGRxY4YxA1oSA6WWPSYZsxMI+VeDykRd66arYytwmnHXgYXF7Blm2rJG7H7GQAqWvUTNgkX9suqwyFx2FnG2X5enZSLRjUvPaVOe1jECw7WXP4z4r8CqN9MayqC2OrCoNTCA41eyHGb7okIgru1UEpGN3yH7JpFdQhyU+HsZpHLvbZuVAb3OGm7b11BityY1RKKHVQToorQcQPbrSFlyGWMwYQNx+L9RxYyATqz8XPSN0uI/hjA7eJUWjCJG29JTGYPE0aVHVao9gVKX0NYlQRWjYe8iQd/XtWT0fKR0fo6NC7CY6UVAswEO000dFBQ+JQNbHR5g9zn9YZx3AuJwSGdQjZ6L8ezT45lwAFavQll0Z2vV/DE+h+yroX9IkzPEuzy8lWFKcMID+9rUnW2WKfidm0CXHzKZnkuNUZg8nE3CFVROX+XmvtNPcfjoCHkBhGzvLqrrYWEP9IfwUP11E7nV6xH1Xpvv8lOJ/cNCiwuu+48aacag9JFnewqohZRMISqvRopxOhYED0dQxp8sSnewJaZQEfHTjsZLnSfK+9zkhPW1IMwZY8Fioqz/jkrChjPSsC9bHZ1w9wvruvENjUWNsBFcOUM4IGRx4U0aQ==
    server.secretkey: AgA0XQNZ9DiEmiJvQ3heHH/vr4GRfLciJ6FWTUcX8mWKO5CMvJ/FkWEOABcZ+BsVA/LGOGa+SeOXXVlRKFy7gT/Duf1G4xyrf1aZ699Y7RLARD65zOPlE86/8zd4ZHAxnrgNhmKy94gDE7ejkpUA+l2Ut4ZTk+NGHuCXuKAJ6n5frX1AIjbIZJB6m+Si4wuFFDpTyk44MRedgV3vcJsBKVpzeZ23AjdpNRb1UoCF1UAnaEU6fCTFWC4BqWlNfnE80yc8M+0QMTRSriQ06tg3Yv8OQ9LnVAPTa1gHrkQWJdMaUZ9oOEXpHZ+FwvqAum2SRiGuPBv+INjW9RBH67jHaEw7TaW2Mg6E5OQQkDehOYNDXwH5nO+p3D8fO8W921KVDl2uwUljRRGVAUlTGF9rQN16HOfSppQUwrLyjzX071Ry6NWcVGm3124MBpJev7EHNgpeswiycq5sUqCWpOgzRrih1x6C/6Ser9bunvAocg7Eb8VIG8o8TUI1yEm3cmS+lFY/WDKz8JrJkrQbPNGsIRcNzwRcEw2BpOEa2igqpdQdr2SWsiT/hqCsSO5T1ub4xzKuc/hAi7bzP/aHna11Ks8j4aF6+p651ch0C/7o2WEs8TQDOAmSdzhq8TIyLUBO8yAK/g/+kveszkTMD4h7xKhB7VNeGRR+DsY4EDk4PxAZousZHaUgph8JmiNfoapnLtB2S7T6O+8ITwu1v//yCii07OKUwrd+dTy+pdfiYf/zMZapowet/ghEDiwEjw==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      name: argocd-secret
      namespace: argocd
    type: Opaque
