apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wazuh-filebeat-cert
  namespace: wazuh
spec:
  secretName: wazuh-filebeat-cert
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - client auth
  commonName: filebeat
  issuerRef:
    name: wazuh-ca-issuer
    kind: Issuer
    group: cert-manager.io
