apiVersion: apps/v1
kind: Deployment
metadata:
  name: immich-database
  namespace: immich
spec:
  replicas: 1
  strategy: 
    type: Recreate
  selector:
    matchLabels: 
      app: immich-database
  template:
    metadata:
      labels:  
        app: immich-database
    spec:
      securityContext:
        fsGroup: 999
      containers:
        - name: immich-postgres
          image: ghcr.io/immich-app/postgres:16-vectorchord0.4.3-pgvectors0.3.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: immich-configmap
                  key: DB_USERNAME
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: immich-secrets
                  key: DB_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: immich-configmap
                  key: DB_DATABASE_NAME
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
              subPath: pgdata
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: immich-postgres-pvc