apiVersion: apps/v1
kind: Deployment
metadata:
  name: immich-machine-learning
  namespace: immich
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: immich-machine-learning
  template:
    metadata:
      labels:
        app: immich-machine-learning
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 2
              preference:
                matchExpressions:
                  - key: gpu
                    operator: In
                    values:
                      - "true"
      containers:
        - name: immich-machine-learning
          image: ghcr.io/immich-app/immich-machine-learning:release-openvino # Intel iGPU
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "4Gi"
              cpu: "2"
          ports:
            - name: http 
              containerPort: 3003
              protocol: TCP
          volumeMounts:
          - name: igpu-device
            mountPath: /dev/dri
      volumes:
      - name: igpu-device
        hostPath:
          path: /dev/dri