- name: Setup K3s Main Server
  hosts: k3s_main_server

  tasks:
    - name: Install K3s with Curl
      ansible.builtin.shell:
        cmd: curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="server" sh -
        creates: /usr/local/bin/k3s # Check if K3s is already present in the machine
      become: true
      environment:
        K3S_TOKEN: "{{ k3s_cluster_token }}"

    - name: Wait for K3s Status
      ansible.builtin.pause:
        prompt: "Waiting for K3s to become ready"
        seconds: 30

    - name: Verify K3s Installation
      ansible.builtin.shell:
        cmd: kubectl get nodes
      register: k3s_nodes # Store output in a variable
      become: true

    - name: Print K3s Nodes
      ansible.builtin.debug:
        var: k3s_nodes.stdout_lines
