apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: bitmore-nut-exporter
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  jobName: "nut-bitmore"
  staticConfigs:
    - targets: ["nut-exporter.monitoring.svc.cluster.local:9199"]
  metricsPath: /ups_metrics
  scheme: HTTP
  params:
    target: ["192.168.10.1"]
  relabelings:
    - targetLabel: instance
      replacement: "bitmore"
    - targetLabel: ups
      replacement: "bitmore"
    - targetLabel: mfr
      replacement: "Bitmore"
    - targetLabel: model
      replacement: "U1200LCD"
