---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: nut-exporter-secrets
  namespace: monitoring
spec:
  encryptedData:
    password: AgCa1WQ2XWTwxtL9UQp6EwQ74sKaUgbrv/YYZLOzf8TE78GoNyT+BjV1zSWXqdTQWU62vy+FOdCUiYmRAV9q8MkpPgSJurU6EnG8t6CVZQi/r5eu4ujTZrWgIR6baTPyzQREBuUW4/BZXar+Fnp7Wm+2nBVL89ihAB/KJPbmj2JXeKl7oaZcsc9BWnY5OvYbAjgLFpHsvnsQHDfJzT7x8afF2uYboKzGbI+Shi3VA0kZ7qR/LczO0aWLnRqZWB1LAnzHCgr8JCtPdxQIYO2DOtrdKaeQSTcuoT6CwoBFjroTQO1z8vtXstgBTvlYlQ4PluM6nE2tiex+CkKdfV5GxPU3jALNN4SAKGeKUpYAt+eG2jxWq5OGxCNTLC5dxG5zxXOGEEG6wpDYoRrats0hmrwJlh7hupcMDpVlMsNzbrDEXSRlauOO7gq/lH65DW1UT7uNOeGloeykqPkNQswCkEZ6UehuMZh2YPH6MZe0G5/2Vzv8jM5cXylysAaz6MVA039GJP4ZvKK3FMdUHxErbBN9uehRFl40eTQHQmFaM/D0xG/1YT/82sKYP/B74D5SxMVG6ffxQcxjrMRAbwPV3wzCsmNJgs6ApwhrCqyj0jcXka+W5hxuh2Fts9KfuTnxbrWz8ojxkbFt3U8sV42OezVcykR5orkgaLcDhThH/NtpGovMNsCljf5ux1bJNQyXol9wo8TdG/E=
    username: AgA1ix6159D9wYhaWPs5Y55t44St8vBNjvWNWvNPH4MYuth4qJgOGkjAnQ2l7Omq2m9xZQJz9sgzob25L5uueyWd1+h4PqepkfkT3Ua/GYvy295GHqwEhxgBkMUiC3lVy20QiTU8bHvwUmX2715W1ZVv1ETQA+apflaUh8OeqN4eChlhuBOd422gYyl/8Tv+lwXsbnB+c+KHQ3QZrpDAUuVRoupzdsqOISfo3v7b3UjoZVEwdHboZMOdas4a9p5iAI8/Rh6xPhHBmTj2W2bHKIcGOIazk1UIEvQ6hFWy4Gs8QW0QdlTkyaDuVmzncM8d6FO3tZFsvsD4eNoDkCSlJgRQ/oLv4EoGn2hXshHN78ftlhjSO+WWLxez22pDc4KoX6whOylokw38c6pgRiuBFTa64coStKnv62DbBZ0amjHy8eGkhVX7i6nX56laJMmi5EVt0XLShhOQVgjAYDhFrePsVu2ULWEWALr5G8vVlCjlOg1qrv00qOKPZi32jUBLH0lJeVJF6VzPF9OH47jP9rqLRd6zdcY3gNlFplVK89vHcHcz9g4/rk23f6TGTgMLX0uA8D0r53QnQs84am59nv9KPlQPncSauhI+bb3+d7GWLkHbSFdNikJnrkfGijc/lRT+wzq7ydz85UllD5lSGs4HRJB2ZnLn1fAdW4zbTd120g+/N/f9fhOydsNDq0/yuMRNHCuK7hnMsY8KEA==
  template:
    metadata:
      name: nut-exporter-secrets
      namespace: monitoring
    type: Opaque
