---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mariadb-secrets
  namespace: databases
spec:
  encryptedData:
    MARIADB_ROOT_PASSWORD: AgBIknPTYfC7OFbaWBdJBHQNN6PUHDlKVfDiGR60y8F+9WwU7n4SI+d7cnG9iIoJZVd6G5JrJIMxmF1abNbiYRR/pdLjSsshp8EN/AM61H89PgNQ7S8ErXacd25t4hFRa+SpRWXhgEdqeVQ/abNNCu8xKlWW23kzlA/ag3NGH+kqm0YmNR6mEpR6x341X+UGSw5Ccn0d8RK+w7lLaWs7EofLn/zL2i5vmdHwP+RABrjYo90odYpUEccdmC47CD1JY7KtkqBZ2OecxK721Wcf4U45B9xJqQ0kL5wtfo51SBotRgAcQatu5htO8TETdFl1Sot4G5Md6JeFXMkKwXaJUVrJmTtGy4M+Jlabo6OmSbsp/Ek4d2ziv0zMUnkvOnUXd3x39qpG1dYkOT005f2Ui/h+gZe1Lxln+Pdl+CnsKfNh5HsDh+B9T+IbFBcw2Lecji4gA9VX8jf8HCzkeG+IVOiwuqcGIMEI4v4vkUimSehkBNZ7Pg7MBO8/kaK37OPW6LEEyayqF3CozJgDEaCbv1OaP2QhaXUofa0Vy6hi0MDDmJNo8Xck+bSPva+7PhSHJIgzZ37ILHnO88+LFI91DwiyceHbjKaLyaq/H8VUrKfgbBDOSLhTQKQHe0ToMhwQV2fqOEL8l/Q+4QOrF1W4UpmVEIH+xXZLFiGcZ/wmR8nLJSsZLWX77LPc2RqHT2UqaPvYMw1yHYzxl3cUA89Mww==
  template:
    metadata:
      name: mariadb-secrets
      namespace: databases
    type: Opaque
