apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authentik
  namespace: argocd
spec:
  destination:
    namespace: authentik
    server: https://kubernetes.default.svc
  sources:
    - repoURL: https://github.com/goauthentik/authentik
      chart: authentik/authentik
      targetRevision: 2026.2.2
      helm:
        valueFiles:
          - $values/k3s/apps/auth/authentik/values.yaml

    - repoURL: https://github.com/manos-grigorakis/home-lab.git
      targetRevision: feat/authentik # TODO: Update to main
      path: k3s/apps/auth/authentik
      ref: values
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
