apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudbeaver
  namespace: argocd
spec:
  destination:
    namespace: cloudbeaver
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/manos-grigorakis/home-lab.git
    path: k3s/apps/dashboards/cloudbeaver
    targetRevision: main
  sources: []
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
