apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: immich
  namespace: argocd
spec:
  destination:
    namespace: immich
    server: https://kubernetes.default.svc
  source:
    path: k3s/apps/media/immich
    repoURL: https://github.com/manos-grigorakis/home-lab.git
    targetRevision: gitops/argocd
  sources: []
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
