apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres
  namespace: argocd
spec:
  destination:
    namespace: databases
    server: https://kubernetes.default.svc
  source:
    path: k3s/apps/databases/postgres
    repoURL: https://github.com/manos-grigorakis/home-lab.git
    targetRevision: service/paperless-ngx
  sources: []
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
