apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wazuh
  namespace: argocd
spec:
  destination:
    namespace: wazuh
    server: https://kubernetes.default.svc
  source:
    path: k3s/apps/monitoring/wazuh
    repoURL: https://github.com/manos-grigorakis/home-lab.git
    targetRevision: main
  sources: []
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
