---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mysql-secrets
  namespace: databases
spec:
  encryptedData:
    MYSQL_ROOT_PASSWORD: AgANG1QRz34nsGVRtp07k7thw6xHwGc43scvXPZeJ/uWC+PV9i1rlHfxvoX4YTR8ti2htILoObe5oTtqBRx+G6z0hUowI6hVVe2hszE9VCvrtuXzcciDHp8qyx61st1B/QK4qjjqQ/glY8pQuiGTA2Cg0+MW+egsm9IW+SlR+VBSx3oAbFGH7retQwhJjn4zkLjGjz3JdpqPT+xW5+ZMxlB+Amli1jVNla3ZCZCfjbs3s9RYwYG88isYoxlPFqZACSh839TOn85AryPVCnAQdZnWWjTDdrFjg61vl1od3ol7Q5I/J8ekxsvEPJY7ck6WeMUSf3JPeiXfHh80cT0pR/p30lTR/+h9PZqJWR1ErvNoGIio9xFgFTvcQvrL2GK2kT+zLZp/U7jyKWpYJPNWRLIbJp5LB56bKXWg+GRC8Wys3cUJUTwGyKqEAZXCaZOjV0x5VhRbR2df3om2YgyfxwDhj+KjsMBYn8bgmLwJ+ML+OU4iAXfBrT8pvLmJDQsEVBDs/LXZXlO12dp65HXayT2lZdedZaEenKXAiJKrWNjLUPn8HT+6MP/GigI4nkegXmIig8r5jbuyLwMpv1b7P2jTUYN5YHEsGBZexNv+7d2gaouq1JAjqhAp8d5/J2tqOOO1a+FYFcjOZ2h1IJL0fXbqK91PqvZAD9X/xCw8JjCwkoZywXXFfMuNan14zark5Whg2iyMkyORLIUfJ0mvpYTA
  template:
    metadata:
      name: mysql-secrets
      namespace: databases
    type: Opaque
