services:
  pihole:
    container_name: pihole
    image: pihole/pihole:2025.04.0
    ports:
      # DNS Ports
      - "53:53/tcp"
      - "53:53/udp"

      # Default HTTP Port
      - "80:80/tcp"

      # Default HTTPS Port. FTL will generate a self-signed certificate
      - "443:433/tcp"

      # Uncomment the below if using Pi-hole as your DHCP Server
      # - "67:67/udp"

    environment:
      # Set the appropriate timezone for your location
      TZ: ${TZ}

      # Set a password to access the web interfaces
      FTLCONF_webserver_api_password: ${PIHOLE_PASSWORD}

    # Volumes store your data betrweern container upgrades
    volumes:
      # For persisting Pi-hole's databases and common configuration file
      - "./pihole/etc-pihole:/etc/pihole"

    cap_add:
      # See https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
      # Required if you are using Pi-hole as your DHCP server, else not needed
      - NET_ADMIN
    restart: unless-stopped
