services:
  pihole:
    container_name: pihole
    image: pihole/pihole:2025.04.0
    ports:
      # DNS Ports
      - "53:53/tcp"
      - "53:53/udp"

      # Default HTTP Port
      - "80:80/tcp"

      # Default HTTPS Port. FTL will generate a self-signed certificate
      - "443:433/tcp"

      # Uncomment the below if using Pi-hole as your DHCP Server
      # - "67:67/udp"

    environment:
      # Set the appropriate timezone for your location
      TZ: ${TZ}

      # Set a password to access the web interfaces
      FTLCONF_webserver_api_password: ${PIHOLE_PASSWORD}

    # Volumes store your data betrweern container upgrades
    volumes:
      # For persisting Pi-hole's databases and common configuration file
      - "./pihole/etc-pihole:/etc/pihole"

    cap_add:
      # See https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
      # Required if you are using Pi-hole as your DHCP server, else not needed
      - NET_ADMIN
    restart: unless-stopped

  netdata:
    container_name: netdata
    image: netdata/netdata:latest
    ports:
      - 19999:19999
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    volumes:
      - ./netdata/config:/etc/netdata
      - ./netdata/lib:/var/lib/netdata
      - ./netdata/cache:/var/cache/netdata
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/os-release:/host/etc/os-release:ro
    environment:
      - DO_NOT_TRACK=1
    restart: unless-stopped
