apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-pvc
  namespace: plex
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi
