---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: plex-secrets
  namespace: media
spec:
  encryptedData:
    PLEX_CLAIM: AgCIZVKvkWn7o8pEbbN0q0ldJMe3buGhEFEz/QSjBH3JtCcK+BrI70dLVqQb4GU5yCos11rqkIZzEo9BU4PhUwrepY2SUt+v5JaO7zvri/xjpZuEWAlJHZK35OtAFvywxYRbzwodAEGIIjPIuqq58V4ULuh2RXyVbywefCDZxWxK/8+EtHr6lTMxpPW1hM0+I9uiRCU8LoaHgFbdhkAZHKNG6iNaXRVxBpQQkJwMlFCDzPiH+Wkp0gwmF1JcPEzxln/cuID72R9IDRAPNUUhdtUqTiF1qCg4DXGvZdZN8Rg7XnHLlKOFleTaSieN/4/B23eUYxOI3uM3DC7WsmLn55Jr9SwP7nJPz+l718j4j4W7IB9PW0agZqIh468r3utm9c4LscvPfSyaOnTWA6RENh8M8urpBausEF0rUmRvwsibL7BqVPT3FTk1bAQdJigPZq8ndGzmcWM50CTV1tbbS+Xm0uRgAg91RTqm922SsKiWPCZxS59c5+vuARiO/LFNswa2eBuDkVehZ3V75TsG04oiGWoB+N0PU/UPyByO7yAlLUO8HEbhw0K5zXNb13T6WzdRTeYfz50hXMxAx4YwXfH3kH1Nu9Ktm/mFqAK3yyW9CSFvbbCf9wRNicC1+QpNx7e/klvBZqJenSuaLVt5Inr8S8mWOQeZEewXiDKioM/tbZiO8RWQ9gpR0xYElBWQcwRPD/G4SyqDA+16P23LgW1hmSC+WqxmQtnwyg==
  template:
    metadata:
      name: plex-secrets
      namespace: media
    type: Opaque
