---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: plex-secrets
  namespace: media
spec:
  encryptedData:
    PLEX_CLAIM: AgDgaP+EkXQJ26dKOBFWCn+4TGMhO0MbzYT183Y0MvKgSsyysUg+leotSj/H2rpGdRyer3q3Qki1B0erh8sc5ch0Q+RUUlmTbom5mUe1ZLIx4sGwexec9Z8Hi9POZQ0yXk7p07K8cA7I3bjWXbSofCPaUGFxg1C8pQCVjioBskxfkLfKYUgmYy9jzQtdnhDI4SZizmWNKGBt8PvRmAU5BPS/+zl1JoHg7uaDW3yCzWNq0bIPOLx9jznW0DUrbq4boMUBlyOTUdqFDeXUfOSH9XhQMCMbPGPf5RodI9pveKK2sIiuKWUh1xcHHMmCw9KYnacvnSIKxvoNCe2oxxXRAqYFX5+Uzmt9t4rRMTKvyY6Uzw60+mJrr3NZgBd3VlDFzolFUMOYDjcU4shQImUl137dhRfDG+bEJwGhDQZBRjvCmqUZDgULI3QlbheB2KU+1WxCR8wo2qmQ35x06LCNFycLCCIEgd6PfCUc1eqxl3LE9mqHJXmLWlST/LyOHyoJDmAgKrSlmHIhfJh1N9x/JcY2XBzICIYxi7HWg6R2AZX2SxthppSeouefs0G1J5EXzBEu1n2L0Ntw8QTxNA8ecShTj3bANL73i01gwc93kUTf0KbptXEMNCdhWgOqZl2ko2Kl0I4QThLvaSNJ5ohkPwWuh5r4PNpHnXIyE3MHAuiEFcm6FgWyOC+sunnXBNc6h/TEx7ucf25jjV1aBGRNU8NYmLHSRY2Wo88k6w==
  template:
    metadata:
      name: plex-secrets
      namespace: media
    type: Opaque
