---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: authentik-secrets
  namespace: authentik
spec:
  encryptedData:
    postgresql-password: AgB+4hnoOh+MuI6rAQQnUgaTHEeCugLap3HVStBw6FGOODK9qPoGPHcsYgrrPgbmhMYK+qPwaZWgutvYMJ42lis8xGsJZZB+2gPi6sKGjFe/XM5NljHgcIQtorRll4WqLDPGeuPnxk8EiMTaXgfZ/6QqRapSBnTa+PInaP5q1gQsDcs9Y2JaCvso8GTsYuNGCY4eZ3c6+/R8NdAU6fkEhgpvhoNZH6g1K3jQuvTGKTW7c5RMehARIDJQL8f7AgGuVxjtVaw6gmb4l+gf+Dd9TUuQ0q8Bs8jTWVTSIkO5ZiREvs/eC/xRrZRS5Tok4n4BJiP/1IozEBze+JPbTGgl4VBsLpiWKMv1+oSD4YzvSllAP8fVtkq7qxaqLroJnGw/DagD021TA1kb03x/CAqpiNa3QvlmpSelJAZBYU/0cFM3rHZzoiJf8A31ussHWN1nWPDX/mLy1WSkJSyD3PoIypIT0CL3eD4VVRqHYmfqD7UM7hfHERivcmzWanZKnlBMBbfQFydsKGbjVLivBgpnyatD5vbuRWm3wMmnUPEIuChz+6oqnPl4p91CAbwEpeikHhOAv1CVnvnETfWcdudqSJT+oz/8KPpsIW7ci7HZa2f4HPky+kvGtFurha8G0pEpVbX7iUxtpi1GaYtVUapOBhJiKT6G4qKU6buj2J/ksK3m04U5FBmLpWpmRT7F0SEBnID8CF1Rr0FWePZirVwD5pVpL3qhacabz82ukZh03Ocl0dVPH+QtDAZ4QERjH0T8BKjNonntu5qpU2rpTJu3eDCOuKmZ5g9fjP0iXBK2lJQRYA==
    secret_key: AgBdI98VFzffVgksT9t4OsW+16gT5UwXEWluBBhuOzln7oi98tvTRuKtloMbTxhB39DPuLq5pH07c8q/ctzIWkFGhzcvDRFx81/pOiW3r7n2BVtnrbTbULu9nA5n31JSIejEnZlbK6SOFXJotVmFEIwoF9sXnx6XOi5wnYUwsaHCRh2jbV/KBQgTiv6GltWfQO6LeK4a2/vRUpuZ0X2E3oxlMPdhTdeN8S4eJ9VT10drtEliqJgWGms4kMbF5iQTEwCBvPdXiJer7awdv13FuiunhXxsFRqbZu7g2SeLw47+yvXwvCTtOsr1mNHUUxStqwZRieuWUvQE3oLyEtpUumGPjv0ilzaOB8QfH2XQIRgt3rIf1YBmT0temDiZncgFTLbffHa8ZZjl3m+LOY4q0lGJKt4i/S5C26TSykQ7IrVCFUybxs1pToRb/VsTV7PPmFZ4nrKp7WWAyg4qnLTr3f+hAcnV348L9hhWq9cyTuYLLJ/rw09ccZUPsiHq2c0CHe+QXU5cIDNQsVVahO04gCxes11e5snIs/FGMTPTxsFDnYdYE1DmSQiLj+wkkPyVV4WbcO7mDb2AP8gDir3DNcVewBTk8CnFLtC0bv9R+RVU1aGmXjVorQpzSBenO70/ZPflYnZR/XY4NUiofAIS2yVZ+Z9CytFj3WFVuH6dvdkR6XwDrAq4lPi33Nax/pnb/aqH7ETTpjASot9xRmw/FgnW1/85woGP+8yrJl5U56uakP/aCH4h2phyAfAzbLuWJYlGsfPmyswwMcfGumGYX0uXOIwFhZz0btOVdT4DHjWJ9g==
  template:
    metadata:
      name: authentik-secrets
      namespace: authentik
    type: Opaque
