apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-google-photos-library-nfs-pvc
  namespace: immich
  labels:
    app: immich-server
spec:
  storageClassName: ""
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 3.5Ti
  volumeName: immich-google-photos-library-nfs-pv
