apiVersion: apps/v1
kind: Deployment 
metadata:
  name: immich-redis
  namespace: immich
spec:
  replicas: 1
  selector:
    matchLabels:
      app: immich-redis
  template:
    metadata:
      labels:
        app: immich-redis
    spec:
      containers:
        - name: immich-redis
          image: docker.io/valkey/valkey:8-bookworm@sha256:a137a2b60aca1a75130022d6bb96af423fefae4eb55faf395732db3544803280
          imagePullPolicy: IfNotPresent
          ports:
            - name: redis
              containerPort: 6379
          args: ["--save", "", "--appendonly", "no"]