- name: Set journald SystemMaxUse
  ansible.builtin.lineinfile:
    path: /etc/systemd/journald.conf
    regexp: "^#?SystemMaxUse"
    line: "SystemMaxUse=1G"

- name: Set journald SystemKeepFree
  ansible.builtin.lineinfile:
    path: /etc/systemd/journald.conf
    regexp: "^#?SystemKeepFree"
    line: "SystemKeepFree=200M"

- name: Set journald RuntimeMaxUse
  ansible.builtin.lineinfile:
    path: /etc/systemd/journald.conf
    regexp: "^#?RuntimeMaxUse"
    line: "RuntimeMaxUse=200M"

- name: Set journald RuntimeKeepFree
  ansible.builtin.lineinfile:
    path: /etc/systemd/journald.conf
    regexp: "^#?RuntimeKeepFree"
    line: "RuntimeKeepFree=50M"

- name: Set journald MaxFileSec
  ansible.builtin.lineinfile:
    path: /etc/systemd/journald.conf
    regexp: "^#?MaxFileSec"
    line: "MaxFileSec=1month"

- name: Reload journald
  ansible.builtin.systemd:
    name: systemd-journald
    state: restarted
