apiVersion: v1
kind: Service
metadata:
  name: wazuh-agents
  namespace: wazuh
  annotations:
    metallb.io/allow-shared-ip: "wazuh-agents"
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.10.125
  selector:
    app: wazuh-manager
    node-type: master
  ports:
    - name: registration
      port: 1515
      targetPort: 1515
      protocol: TCP