apiVersion: v1 
kind: Service
metadata:
  name: immich-redis
  namespace: immich
spec:
  selector:
    app: immich-redis
  ports:
    - name: tcp-redis
      protocol: TCP
      port: 6379
      targetPort: 6379
  type: ClusterIP