---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgCYOB210mnfjo9Znsd9qCRfxpY1p1vYMh/cdl5S3a/e72l+UOSUQkWqbZNIolH2oXXc+G6s/kdNpbmGwhzirkauCqZCEt/ajTiWDDwjDQcWWK2W9Ds/gdJTAZAbstE8nSu13z01pjmnyLqHc6yzTyxV/oVoZdlD6MBQzk28sJ/D9vqiMEJBBeaegpNmC6Mj/l+h4jcmXUAfhqDEmdVUOvtf0AEaUeCL0YmPkurNlG2bsz/322T54HzZdsegfgP+lVyXCHN5iSGKEzbZizmwKuGTAkLCHL7f/pFHP0SPWD0QUbFIe6fmvdPVnBHTjX4RdozoiKhHt+8AXZTgFPNWHfIFjA1RsPYxIYPjsNLq2vUKUQblvvlCT/d89lpdHdwWv87ArI/fkUPVinMV3NzProPJJHL3TDAmpk7Q+SyhElxDZEX9QB8gHnImxL6jvexBjPtsCB93WS2op58TBRZvWc12NVU4P2klCvFWntpfqjh91oOGhqMhVaz9VXkNHN41cny6WUV9M5tpnQq7lgRC3IJDa8l6zoe8BxG/cdv7gR65NrTGcoEGeZHPRBdKtLTYYRpbZ/V2YEHKv+vZLosuvO9obOinK38gz3AeHcJ68A+htkmNC9+gmkNvezb+dKSEbXvR73AmKNsrktF39DeLd4mM6lgjLNL9FFYqkRyCb9W83tAwGQKmu6CjM5lMTKmdfPwwG+pZ7i2GqKkzn+K7JvxBo96hd9lZwRcTbhTJRIXINCrKwQyk4alD
  template:
    metadata:
      name: cloudflare-api-token-secret
      namespace: cert-manager
    type: Opaque
