---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgCXrvzBC6G6OcIOKyGS8w0R/dCHBjBqx/bmVpoS1bhPU7aT4bxtb989PvHkEA8EIl2CCIOCWcxITGNVjQ3wc2UFWFiCRxJZzgmpJPg4WD8h8wBXOwFm+HO/y/+yBO9jFv21xJu3ZgT9tNhHoJrWrhYw32BH5IQ/PFTaB+pW5ErB/qQqEwPSz7soGSOgeXhjVYMlyOjHyeWHwFapACqMZAQuoxYb12Y+Trf7bIDP3oTO66nDRZkK9pm2yfncGUEjGZnefychG79R/3NW4jkvWlo+jm04oK3fxW+sn2B2vRHoeuICtu7oixVVundzU2CQHUU2/aXdSZWFCzoEGKAW1Vtr7DpxtIQb52LYM40gORJiSFGmVcJyVWCEORoUR+gqnqK+XHQZkodKdd1EalTsJJJIA4XOXLLkgaOeK/0pcNOXQM8MLj8DMZC7AO57ZnsFk8gmsWG5zLeiOGYOA+mjUGt6531zWA7GyoEVLhC0shAeGMlBi/mqkpBgegHrmWY1Hsbu2AAJwJmNujBtqKCZrUUye4WNzZ+927anHiydhrqvTw1cR4TXJ/79rectaJccCAOAbJnVEMpyEye2/J0kXqDqZKi0YnGkDm/c/aP9/zkKIGoVNsQI85sKr9RZXXIEuCBFzc6mkboTHNnmNIHIUquO5YwJmJZWnsOelaYzrWFz+eLbwHx3ws5HzuYz+ehceoz8sUaPNp+DeisjWwH9BYFisw8e18ORBD5vKAUiioxaCEz7nrdlDqsC
  template:
    metadata:
      name: cloudflare-api-token-secret
      namespace: cert-manager
    type: Opaque
