apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dns

resources:
  - dns-ns.yaml

  - pihole-pvc.yaml
  - unbound-pvc.yaml

  - pihole-configmap.yaml
  - unbound-configmap.yaml

  - deployment.yaml

  - dns-service.yaml
  - pihole-service.yaml
  - pihole-redirect-middleware.yaml
  - ingress-route.yaml