---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pihole-secrets
  namespace: dns
spec:
  encryptedData:
    FTLCONF_WEBSERVER_API_PASSWORD: AgANH+bSRXLgQr8EgrkleoLxrnPzZVoPFPVuRzKGCIZTamX2FW1X2aLLu6iROBucOeWiJl9qujJeSBCBKVzv7kK8y0qdMi1gtQRN0s8/9Vayxsvgzv0q7p5+sH/GsCwW4AYwY3LpO/oXdKRAM/SfFL6zyN5R3s1EfeAWblvZCSIdlDcdMZUVJPdRyUitsrW2lXd6w6MXwb+Gc8YR+s99aqP9Rxe6CiL01CbDBmAvlIbQcFPhFaarMPja8PMpXcsZ0MuqyElW74Fh6g3AgTMVSNQQBVW70Ab/nMLQdp9MJf2F8pQPurgiPISZu3GkG5E+r1WS89EZxhpiOl4M9aFyOQx4g5zj0STvITc4d3cqwftCcgCI6SGBbfhfIFgj0ZgS8UMFX084KykeUWLdTuyNgjzjxcKz8OaXB5rDbmI+y0aIOFZ/QYZW9k+8WH8YMj6IQCQHmmhwOtKVIuz0jnc4kV+Q0l0OMozUARP7hsvywJX7BCSlQ/Ufeh/0PsiQPXChCl07Dj7qTkLV/zaWj3Mkaw8108O3A+UjlghqqBhyGZf5AVTX/j06DTWON79zgtXrokKDJvI9NcbzXhL+rzENrw7Q54zaEiEAoxBLwPo8hocsSFxfwHp6F+pqx24Y48jpYQXENNhFQjJPeVz5yE+ZgPi6H7Ue01IPVLiiae6bVVjsWMUlG0vCaek945ZzEnKtda9NTd0ylMSDjIiSzO4aTF8=
  template:
    metadata:
      name: pihole-secrets
      namespace: dns
    type: Opaque
