---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pihole-secrets
  namespace: dns
spec:
  encryptedData:
    FTLCONF_WEBSERVER_API_PASSWORD: AgCoOUyYse8Vjkcuc2BWQUhdczD8NU6E6VZSkmeqWC2iFxiLD03TvhKb1LYtbIskko4yQcJF/15FKOo6tjzshg0gQdHsRSIWj63eJTOc8cUT027o0W8rgcLZLpxZuEOkBBfKxdGt5S6evriRo9DS1owIvnJH13fokBYRZYBoqC8dc8pwbT7It77uqr/EI1Je7kHesslJJ59TXXlfIlgY5MOlkriUVvOfuGe6BUMKnYJfIqsmRuC3tPv8kwXNekOGCnJd4rMJ6yLYAWu4q8G2hqdQT5ROUsTJdPUab84PFkmLkhXwJER58/dEdwBGi5hBKP+AoEGadRPnyuqFHUqmuJjvisZgzw9Z2CfrFF8MgaCpwzZrr4W2NdwgII21DOV6PCEzEu7t7ySyx02WG8FpOscRNQA9VEZ99QOogQDtTU3t3f8P4jNB2ZXrRJ5A93SYkZRO3S/0RCuK8IXrkWqR+XtyN0nFmZsd5AyEd8FwfhzGaMs0E+hnTUHqXMxTNCGK4tRyaXMdstPmKjGaqTK88psrEJBPWTZk55G/mTDvz4Lk64zmR48isXKTWSjfOzHeM1fpM3AviwZyEymxVs6CK/xflKUmo7HSYPic7RJ1V2Bq+aNZH544pREOV7vlcxpWBS5qg1kQTAvCEDlZxFC/iB4jHQDAyuGsj3CWqBipDsyK30gR3lDww16ys82vABpTwO3XKpSIXAUzpZYUVr3IPfU=
  template:
    metadata:
      name: pihole-secrets
      namespace: dns
    type: Opaque
